// Original bilingual learning content for EnglishMaster. Answer indexes are zero-based.
export const courses = [
    { id: 'english-a1', title: 'Tiếng Anh nền tảng A1', level: 'A1', category: 'Nền tảng', description: 'Bắt đầu từ lời chào, thói quen và những tình huống quen thuộc. Học từ mới trong ngữ cảnh, nghe hội thoại ngắn và tự kiểm tra sau mỗi bài.', duration: '4 tuần', lessons: 4, rating: 4.9, instructor: 'Đội ngũ EnglishMaster', outcomes: ['Tự giới thiệu và hỏi thông tin cơ bản', 'Mô tả thói quen và hoạt động đang diễn ra', 'Hiểu hội thoại ngắn về cuộc sống hằng ngày', 'Đọc thông báo và đoạn văn đơn giản'], color: '#7C6AE6', icon: '🌱' },
    { id: 'english-a2', title: 'Giao tiếp tự tin A2', level: 'A2', category: 'Giao tiếp', description: 'Tự tin hơn khi mua sắm, di chuyển và sắp xếp kế hoạch. Củng cố ngữ pháp thiết yếu qua các tình huống thực tế và bài tập có giải thích.', duration: '4 tuần', lessons: 4, rating: 4.8, instructor: 'Đội ngũ EnglishMaster', outcomes: ['Hỏi và hiểu thông tin về phương tiện di chuyển', 'Kể lại trải nghiệm bằng quá khứ đơn', 'So sánh lựa chọn và diễn đạt kế hoạch', 'Đọc tin nhắn, lịch hẹn và hướng dẫn ngắn'], color: '#22A699', icon: '✈️' },
    { id: 'business-b1', title: 'Tiếng Anh công sở B1', level: 'B1', category: 'Công việc', description: 'Dùng tiếng Anh để cập nhật tiến độ, phối hợp với đồng nghiệp và giải quyết tình huống công việc. Thực hành cách trình bày ý kiến rõ ràng, lịch sự.', duration: '4 tuần', lessons: 4, rating: 4.9, instructor: 'Đội ngũ EnglishMaster', outcomes: ['Cập nhật tiến độ và trao đổi về hạn chót', 'Đưa ra đề xuất và thảo luận phương án', 'Hiểu ý chính của trao đổi công việc', 'Đọc và tóm tắt nội dung có liên quan đến nhóm'], color: '#E8A444', icon: '💼' },
];
export const lessons = [
    { id: 'a1-1', courseId: 'english-a1', title: 'Hello! Làm quen và giới thiệu', description: 'Học lời chào, giới thiệu tên và nơi ở; luyện động từ to be qua cuộc gặp hàng xóm mới.', order: 1, vocabularyIds: ['v01', 'v02', 'v06'], grammarId: 'g01', listeningId: 'l01', readingId: 'r01', questionIds: ['q03', 'q04', 'q09'] },
    { id: 'a1-2', courseId: 'english-a1', title: 'Một buổi sáng của bạn', description: 'Kể về bữa sáng và hoạt động thường ngày bằng hiện tại đơn.', order: 2, vocabularyIds: ['v03', 'v04', 'v14'], grammarId: 'g02', listeningId: 'l01', readingId: 'r01', questionIds: ['q01', 'q05', 'q08'] },
    { id: 'a1-3', courseId: 'english-a1', title: 'Những nơi quanh nhà', description: 'Mô tả nơi chốn, dùng a/an/the và đọc giờ mở cửa trong một thông báo ngắn.', order: 3, vocabularyIds: ['v02', 'v06', 'v10'], grammarId: 'g04', listeningId: 'l01', readingId: 'r01', questionIds: ['q02', 'q06', 'q07'] },
    { id: 'a1-4', courseId: 'english-a1', title: 'Bạn đang làm gì?', description: 'Phân biệt hoạt động hiện tại với thói quen; ôn cách nghe lấy thông tin cơ bản.', order: 4, vocabularyIds: ['v01', 'v03', 'v16'], grammarId: 'g03', listeningId: 'l01', readingId: 'r01', questionIds: ['q04', 'q05', 'q08', 'q10'] },
    { id: 'a2-1', courseId: 'english-a2', title: 'Sẵn sàng cho chuyến đi', description: 'Hỏi giờ tàu, nhận biết thông tin thay đổi và kể về một chuyến đi đã qua.', order: 1, vocabularyIds: ['v20', 'v22', 'v23', 'v15'], grammarId: 'g06', listeningId: 'l02', readingId: 'r02', questionIds: ['q13', 'q14', 'q17', 'q19'] },
    { id: 'a2-2', courseId: 'english-a2', title: 'Chọn điều phù hợp', description: 'So sánh lựa chọn và xử lý những thay đổi nhỏ trong kế hoạch hằng ngày.', order: 2, vocabularyIds: ['v05', 'v06', 'v10', 'v20'], grammarId: 'g08', listeningId: 'l02', readingId: 'r02', questionIds: ['q11', 'q15', 'q16'] },
    { id: 'a2-3', courseId: 'english-a2', title: 'Lên lịch hẹn và kế hoạch', description: 'Nói về dự định, kiểm tra thời gian rảnh và xác nhận lịch di chuyển.', order: 3, vocabularyIds: ['v07', 'v15', 'v13', 'v23'], grammarId: 'g07', listeningId: 'l02', readingId: 'r02', questionIds: ['q16', 'q18', 'q19'] },
    { id: 'a2-4', courseId: 'english-a2', title: 'Mua sắm và ăn uống', description: 'Dùng lượng từ phù hợp khi nói về đồ ăn, hành lý và việc mua hàng.', order: 4, vocabularyIds: ['v08', 'v09', 'v22', 'v03'], grammarId: 'g05', listeningId: 'l02', readingId: 'r02', questionIds: ['q12', 'q13', 'q15', 'q20'] },
    { id: 'b1-1', courseId: 'business-b1', title: 'Cập nhật tiến độ công việc', description: 'Thông báo phần việc đã hoàn thành, trao đổi về hạn chót và yêu cầu hỗ trợ.', order: 1, vocabularyIds: ['v11', 'v12', 'v13', 'v17'], grammarId: 'g10', listeningId: 'l03', readingId: 'r04', questionIds: ['q21', 'q22', 'q23', 'q28'] },
    { id: 'b1-2', courseId: 'business-b1', title: 'Cộng tác và phản hồi', description: 'Mô tả người và nhiệm vụ bằng mệnh đề quan hệ; hiểu ý kiến và lợi ích của cộng tác.', order: 2, vocabularyIds: ['v18', 'v27', 'v28', 'v29'], grammarId: 'g12', listeningId: 'l03', readingId: 'r03', questionIds: ['q22', 'q26', 'q27', 'q29'] },
    { id: 'b1-3', courseId: 'business-b1', title: 'Đề xuất và phương án dự phòng', description: 'Dùng câu điều kiện để thảo luận lựa chọn và xác nhận phương án cuối cùng.', order: 3, vocabularyIds: ['v14', 'v15', 'v28', 'v30'], grammarId: 'g11', listeningId: 'l03', readingId: 'r04', questionIds: ['q21', 'q24', 'q29', 'q30'] },
    { id: 'b1-4', courseId: 'business-b1', title: 'Từ cuộc họp đến hành động', description: 'Diễn đạt quy trình với câu bị động, xác định người phụ trách và chốt bước tiếp theo.', order: 4, vocabularyIds: ['v12', 'v17', 'v18', 'v30'], grammarId: 'g13', listeningId: 'l03', readingId: 'r04', questionIds: ['q23', 'q25', 'q28', 'q30'] },
];
export const questions = [
    { id: 'q01', skill: 'vocabulary', level: 'A1', prompt: 'Which word means the first meal of the day?', options: ['Dinner', 'Breakfast', 'Lunch', 'Snack'], correctAnswer: 1, explanation: 'Breakfast là bữa sáng, bữa ăn đầu tiên trong ngày. Lunch là bữa trưa và dinner thường là bữa tối.' },
    { id: 'q02', skill: 'vocabulary', level: 'A1', prompt: 'Please be _____. The baby is sleeping.', options: ['noisy', 'hungry', 'quiet', 'crowded'], correctAnswer: 2, explanation: 'Quiet nghĩa là yên tĩnh, phù hợp với việc em bé đang ngủ. Noisy mang nghĩa ngược lại: ồn ào.' },
    { id: 'q03', skill: 'vocabulary', level: 'A1', prompt: 'The person who lives in the house next to yours is your _____.', options: ['neighbor', 'teacher', 'driver', 'customer'], correctAnswer: 0, explanation: 'Neighbor là hàng xóm, người sống gần nhà bạn. Các từ khác chỉ nghề nghiệp hoặc vai trò khác.' },
    { id: 'q04', skill: 'grammar', level: 'A1', prompt: 'My sister _____ a student.', options: ['am', 'are', 'be', 'is'], correctAnswer: 3, explanation: 'My sister là chủ ngữ ngôi thứ ba số ít, nên động từ to be ở hiện tại là is.' },
    { id: 'q05', skill: 'grammar', level: 'A1', prompt: 'He _____ to work by bus every day.', options: ['go', 'goes', 'going', 'are going'], correctAnswer: 1, explanation: 'Every day diễn tả thói quen nên dùng hiện tại đơn. Với he, go thêm -es thành goes.' },
    { id: 'q06', skill: 'grammar', level: 'A1', prompt: 'I eat _____ apple after lunch.', options: ['a', 'some', 'an', 'many'], correctAnswer: 2, explanation: 'Apple là danh từ đếm được số ít và bắt đầu bằng nguyên âm /æ/, nên dùng an.' },
    { id: 'q07', skill: 'reading', level: 'A1', prompt: 'What time does the bookshop open on Saturday?', passage: 'Our bookshop opens at nine from Monday to Friday. On Saturday, it opens at ten and closes at four. It is closed on Sunday.', options: ['At ten', 'At nine', 'At four', 'It does not open'], correctAnswer: 0, explanation: 'Đoạn văn ghi rõ On Saturday, it opens at ten. Giờ chín áp dụng từ thứ Hai đến thứ Sáu.' },
    { id: 'q08', skill: 'reading', level: 'A1', prompt: 'How does Hoa travel to work after her walk?', passage: 'Hoa walks in the park with Minh every morning. After twenty minutes, Minh goes home. Hoa takes the bus to the bookshop where she works.', options: ['By car', 'By bike', 'On foot all the way', 'By bus'], correctAnswer: 3, explanation: 'Câu Hoa takes the bus to the bookshop cho biết cô đi xe buýt đến chỗ làm sau khi đi bộ trong công viên.' },
    { id: 'q09', skill: 'listening', level: 'A1', prompt: 'Which apartment does Ben live in?', audioText: 'Hi, I am Ben. I am your new neighbor. I live in apartment twelve. My friend lives in apartment twenty.', options: ['Apartment eleven', 'Apartment twelve', 'Apartment twenty', 'Apartment two'], correctAnswer: 1, explanation: 'Ben nói I live in apartment twelve. Căn hộ số hai mươi là của bạn anh ấy.' },
    { id: 'q10', skill: 'listening', level: 'A1', prompt: 'What does the customer order?', audioText: 'Server: Would you like tea or coffee? Customer: Tea, please. And a glass of water. I do not want coffee today.', options: ['Coffee and water', 'Tea and juice', 'Tea and water', 'Coffee and tea'], correctAnswer: 2, explanation: 'Khách gọi trà rồi thêm một cốc nước. Câu cuối xác nhận hôm nay khách không muốn cà phê.' },
    { id: 'q11', skill: 'vocabulary', level: 'A2', prompt: 'Can I _____ your dictionary? I will give it back tomorrow.', options: ['borrow', 'lend', 'keep forever', 'sell'], correctAnswer: 0, explanation: 'Người nói muốn mượn rồi trả lại nên dùng borrow. Lend nghĩa là cho người khác mượn.' },
    { id: 'q12', skill: 'vocabulary', level: 'A2', prompt: 'Keep your _____ to show that you paid for the shoes.', options: ['recipe', 'itinerary', 'invitation', 'receipt'], correctAnswer: 3, explanation: 'Receipt là biên lai chứng minh đã thanh toán. Recipe là công thức nấu ăn, dễ nhầm về cách viết nhưng khác nghĩa.' },
    { id: 'q13', skill: 'vocabulary', level: 'A2', prompt: 'Which word refers to the bags you take on a journey?', options: ['Traffic', 'Luggage', 'Furniture', 'Weather'], correctAnswer: 1, explanation: 'Luggage nghĩa là hành lý mang theo khi đi xa. Đây là danh từ không đếm được trong tiếng Anh thông thường.' },
    { id: 'q14', skill: 'grammar', level: 'A2', prompt: 'Did you _____ the museum yesterday?', options: ['visited', 'visiting', 'visit', 'visits'], correctAnswer: 2, explanation: 'Sau trợ động từ did, dùng động từ nguyên mẫu visit. Yesterday cho biết thời gian quá khứ.' },
    { id: 'q15', skill: 'grammar', level: 'A2', prompt: 'This bag is _____ than that one.', options: ['cheaper', 'cheapest', 'more cheapest', 'most cheap'], correctAnswer: 0, explanation: 'Than cho biết đây là so sánh hơn. Cheap là tính từ ngắn nên thêm -er thành cheaper.' },
    { id: 'q16', skill: 'reading', level: 'A2', prompt: 'What will the friends do if it rains?', passage: 'Hi everyone! Let us meet at the park gate at eleven for our picnic. If it rains, we will go to the café opposite the library instead. Please bring a sandwich if the weather is good.', options: ['Meet inside the library', 'Cancel all their plans', 'Have a picnic in the rain', 'Go to a café'], correctAnswer: 3, explanation: 'Tin nhắn nêu phương án khi mưa là đến quán cà phê đối diện thư viện, không phải vào thư viện.' },
    { id: 'q17', skill: 'reading', level: 'A2', prompt: 'Where should passengers wait for the bus today?', passage: 'BUS STOP CLOSED TODAY. Road repairs are taking place outside the station. Please use the temporary stop beside the supermarket, 200 meters ahead. All buses will follow their normal timetable.', options: ['Outside the station', 'Beside the supermarket', 'Inside the supermarket', 'At a stop with a new timetable'], correctAnswer: 1, explanation: 'Thông báo yêu cầu dùng trạm tạm cạnh siêu thị, cách phía trước 200 mét. Lịch chạy vẫn như thường lệ.' },
    { id: 'q18', skill: 'reading', level: 'A2', prompt: 'When is Lan available to help?', passage: 'Hi Minh, I cannot help with your presentation on Tuesday because I have a class. Wednesday morning is also busy, but I am free after two that afternoon. Shall we meet at three? Lan', options: ['Tuesday morning', 'Wednesday morning', 'Wednesday afternoon', 'Every afternoon'], correctAnswer: 2, explanation: 'Lan rảnh sau hai giờ chiều thứ Tư và đề xuất gặp lúc ba giờ. Cô bận thứ Ba và sáng thứ Tư.' },
    { id: 'q19', skill: 'listening', level: 'A2', prompt: 'What time does the new train leave?', audioText: 'Agent: Your old ticket was for nine o’clock. I have changed it to the eleven thirty train. It arrives in Da Nang at two. Passenger: Great, eleven thirty is perfect.', options: ['11:30', '9:00', '2:00', '11:00'], correctAnswer: 0, explanation: 'Giờ khởi hành mới là eleven thirty, tức 11:30. Chín giờ là vé cũ và hai giờ là giờ đến.' },
    { id: 'q20', skill: 'listening', level: 'A2', prompt: 'Why does the customer choose the vegetable sandwich?', audioText: 'Customer: Does the cheese sandwich contain milk products? Server: Yes. The vegetable sandwich has no cheese or butter. Customer: I cannot eat milk products, so I will have the vegetable sandwich.', options: ['It is the cheapest item', 'The cheese sandwich is sold out', 'They do not like vegetables', 'They cannot eat milk products'], correctAnswer: 3, explanation: 'Khách nói rõ không ăn được sản phẩm từ sữa nên chọn bánh kẹp rau không có phô mai hoặc bơ. Đoạn nghe không nhắc giá.' },
    { id: 'q21', skill: 'vocabulary', level: 'B1', prompt: 'We must finish by Friday. Friday is the project _____.', options: ['feedback', 'deadline', 'colleague', 'benefit'], correctAnswer: 1, explanation: 'Deadline là hạn chót hoàn thành công việc. Cụm finish by Friday có nghĩa là hoàn thành muộn nhất vào thứ Sáu.' },
    { id: 'q22', skill: 'vocabulary', level: 'B1', prompt: 'You can trust Mai to arrive on time and finish her work. She is _____.', options: ['temporary', 'crowded', 'reliable', 'unavailable'], correctAnswer: 2, explanation: 'Reliable diễn tả người đáng tin cậy, thực hiện đúng điều được mong đợi. Hai dấu hiệu là đúng giờ và hoàn thành công việc.' },
    { id: 'q23', skill: 'grammar', level: 'B1', prompt: 'She has worked here _____ 2022.', options: ['since', 'for', 'during', 'from then'], correctAnswer: 0, explanation: 'Since đi với mốc bắt đầu như 2022. For đi với khoảng thời gian, chẳng hạn for four years.' },
    { id: 'q24', skill: 'grammar', level: 'B1', prompt: 'If I had more free time, I _____ a cooking course.', options: ['will take', 'take', 'have taken', 'would take'], correctAnswer: 3, explanation: 'Đây là điều kiện loại 2: if + quá khứ đơn, would + động từ nguyên mẫu, nói về tình huống giả định ở hiện tại.' },
    { id: 'q25', skill: 'grammar', level: 'B1', prompt: 'The invitations _____ by email yesterday.', options: ['send', 'were sent', 'are sending', 'have send'], correctAnswer: 1, explanation: 'Lời mời chịu tác động nên dùng bị động. Yesterday yêu cầu quá khứ đơn: were + sent, phân từ quá khứ của send.' },
    { id: 'q26', skill: 'reading', level: 'B1', prompt: 'What does the writer see as the garden’s main benefit?', passage: 'The shared garden produces only a small amount of food. However, neighbors who used to pass each other silently now exchange advice and stop for a conversation. For the organizers, these new relationships matter more than the vegetables.', options: ['It supplies all the residents’ food', 'It makes the buildings more expensive', 'It helps neighbors connect', 'It prevents every disagreement'], correctAnswer: 2, explanation: 'Người viết nhấn mạnh các mối quan hệ mới quan trọng hơn rau thu hoạch. Vì thế lợi ích chính là kết nối hàng xóm.' },
    { id: 'q27', skill: 'reading', level: 'B1', prompt: 'Which statement best describes the reviewer’s opinion?', passage: 'The walking tour was well organized, and our guide answered every question patiently. I enjoyed the stories about local life. The only disappointment was the long stop at a crowded souvenir shop. I would still recommend the tour, especially to first-time visitors.', options: ['Mostly positive, with one criticism', 'Completely negative', 'Positive only about the shop', 'Uncertain because the tour was canceled'], correctAnswer: 0, explanation: 'Người đánh giá khen cách tổ chức và hướng dẫn viên, chỉ phê bình điểm dừng ở cửa hàng lưu niệm, rồi vẫn đề xuất chuyến đi.' },
    { id: 'q28', skill: 'listening', level: 'B1', prompt: 'What must An do today?', audioText: 'Manager: Kim can review your guide on Thursday. Please send her the text today, even if the photos are not ready. An: All right. I will send the writing now and add the photos tomorrow.', options: ['Finish taking all the photos', 'Cancel Kim’s review', 'Print the complete guide', 'Send Kim the written text'], correctAnswer: 3, explanation: 'Quản lý yêu cầu gửi phần chữ cho Kim hôm nay dù ảnh chưa xong. An đồng ý gửi nội dung ngay và thêm ảnh ngày mai.' },
    { id: 'q29', skill: 'listening', level: 'B1', prompt: 'Why is the workshop moving to another room?', audioText: 'The workshop will still start at ten, and the speaker has confirmed she can attend. We are moving from Room Four to Room Seven because more people registered than we expected. Room Seven has space for forty participants.', options: ['The speaker is late', 'More people registered than expected', 'Room Seven has a better projector', 'The starting time changed'], correctAnswer: 1, explanation: 'Nguyên nhân được nói trực tiếp sau because: số người đăng ký nhiều hơn dự kiến. Giờ bắt đầu và người trình bày đều được giữ nguyên.' },
    { id: 'q30', skill: 'listening', level: 'B1', prompt: 'What is the final plan for Saturday?', audioText: 'Mai: We planned to cycle to the lake, but the forecast says heavy rain. Ben: Shall we visit the museum instead? Mai: Good idea. Let us take the bus and meet at the museum entrance at ten. Ben: Agreed.', options: ['Cycle to the lake at ten', 'Stay home and call each other', 'Visit the museum and travel by bus', 'Walk to the lake after the rain'], correctAnswer: 2, explanation: 'Kế hoạch cuối cùng là đi bảo tàng bằng xe buýt, gặp ở cổng lúc mười giờ. Đạp xe đến hồ là phương án ban đầu đã thay đổi.' },
    { id: 'q31', skill: 'vocabulary', level: 'B2', prompt: 'The new process produces the same result using less time and energy. It is more _____.', options: ['efficient', 'reluctant', 'ambiguous', 'fragile'], correctAnswer: 0, explanation: 'Efficient nhấn mạnh làm tốt với ít thời gian hoặc nguồn lực bị lãng phí. Câu mô tả cùng kết quả nhưng tốn ít thời gian và năng lượng hơn.' },
    { id: 'q32', skill: 'vocabulary', level: 'B2', prompt: 'After both sides agreed to make concessions, they managed to _____ a compromise.', options: ['perform', 'do', 'carry', 'reach'], correctAnswer: 3, explanation: 'Reach a compromise là kết hợp từ tự nhiên, nghĩa là đạt được thỏa hiệp. Make concessions là chấp nhận nhượng bộ.' },
    { id: 'q33', skill: 'grammar', level: 'B2', prompt: 'Choose the correct indirect question: She asked me _____.', options: ['where did I work', 'where I worked', 'where worked I', 'where do I worked'], correctAnswer: 1, explanation: 'Câu hỏi gián tiếp dùng trật tự chủ ngữ rồi động từ: where I worked. Không đảo did/do như câu hỏi trực tiếp.' },
    { id: 'q34', skill: 'grammar', level: 'B2', prompt: 'By the time we reached the station, the last train _____, so we took a taxi.', options: ['has left', 'was leaving tomorrow', 'had already left', 'leaves'], correctAnswer: 2, explanation: 'Tàu rời ga trước khi chúng tôi đến, tức trước một mốc quá khứ khác, nên dùng quá khứ hoàn thành had already left.' },
    { id: 'q35', skill: 'grammar', level: 'B2', prompt: 'The office is locked, the lights are off, and everyone’s coat is gone. They _____ home already.', options: ['must have gone', 'must go', 'should go tomorrow', 'must have go'], correctAnswer: 0, explanation: 'Must have + phân từ quá khứ diễn tả suy luận chắc chắn về quá khứ dựa trên dấu hiệu hiện tại. Gone là phân từ đúng của go.' },
    { id: 'q36', skill: 'reading', level: 'B2', prompt: 'What is the writer’s main argument?', passage: 'The studio initially shortened every meeting, but repeated discussions continued. Improvement came only when invitations specified the decision needed and someone recorded the outcome. Some meetings now last longer than before, yet the team spends less time revisiting the same issues.', options: ['All meetings should last the same amount of time', 'Recording outcomes makes discussion unnecessary', 'Long meetings are always more productive', 'Clear purpose matters more than duration alone'], correctAnswer: 3, explanation: 'Chỉ rút ngắn cuộc họp không giải quyết vấn đề; nêu mục tiêu và ghi kết quả mới giúp giảm lặp lại. Vì vậy mục đích rõ ràng quan trọng hơn độ dài đơn thuần.' },
    { id: 'q37', skill: 'reading', level: 'B2', prompt: 'Why should the survey result be interpreted cautiously?', passage: 'A training provider reported that 92 percent of respondents found its course useful. The questionnaire, however, was sent only to people who had completed every lesson. Students who stopped attending were not invited to respond.', options: ['No participants finished the course', 'The survey excluded people who dropped out', 'The questionnaire asked about another course', 'The provider reported a completion rate of 92 percent'], correctAnswer: 1, explanation: 'Khảo sát chỉ hỏi người hoàn thành toàn bộ khóa nên bỏ sót trải nghiệm của người nghỉ giữa chừng. 92% là mức đánh giá hữu ích trong nhóm trả lời, không phải tỷ lệ hoàn thành.' },
    { id: 'q38', skill: 'reading', level: 'B2', prompt: 'What can be inferred about the shared document?', passage: 'Before the studio changed its process, absent colleagues often asked for a second discussion. Now, each decision is recorded with a brief reason and a named person responsible for the next step. Requests to repeat discussions have fallen.', options: ['It removes the need for individual responsibility', 'It contains every word spoken in meetings', 'It helps absent colleagues understand decisions', 'It prevents employees from questioning decisions'], correctAnswer: 2, explanation: 'Việc ghi quyết định, lý do và người phụ trách giúp người vắng mặt nắm kết quả; số yêu cầu thảo luận lại giảm. Không có căn cứ nói tài liệu ghi từng lời hoặc cấm chất vấn.' },
    { id: 'q39', skill: 'listening', level: 'B2', prompt: 'What agreement do the speakers reach?', audioText: 'Buyer: We need everything by Monday. Supplier: The full order will not be ready until Wednesday, but I can send the essential items on Monday at no extra charge. Buyer: That will let us start the project. Please send the rest on Wednesday.', options: ['Split the delivery between Monday and Wednesday', 'Delay the entire order until Friday', 'Deliver the full order on Monday for an extra fee', 'Cancel the essential items'], correctAnswer: 0, explanation: 'Nhà cung cấp gửi phần thiết yếu thứ Hai, phần còn lại thứ Tư và không tính thêm phí. Người mua chấp nhận phương án giao thành hai đợt.' },
    { id: 'q40', skill: 'listening', level: 'B2', prompt: 'What is the guest’s position on slower travel?', audioText: 'Guest: Staying longer in one place has made my holidays more rewarding. Still, I would not claim it is always cheaper. Accommodation and local transport can change the total considerably, so I compare the whole trip before deciding.', options: ['It is always the cheapest way to travel', 'It is worthwhile only in large cities', 'It guarantees that transport has no environmental cost', 'It can be rewarding, but costs need individual comparison'], correctAnswer: 3, explanation: 'Khách thấy cách đi này đáng giá nhưng không khẳng định luôn rẻ hơn. Họ nhấn mạnh cần so sánh tổng chi phí từng chuyến.' },
    { id: 'q41', skill: 'vocabulary', level: 'C1', prompt: 'The report links the policy to higher sales, but the evidence is too _____ to support a firm conclusion.', options: ['conclusive', 'tenuous', 'irrefutable', 'compelling'], correctAnswer: 1, explanation: 'Tenuous nghĩa là yếu, thiếu chắc chắn, phù hợp với việc chưa thể kết luận vững. Ba lựa chọn còn lại đều thể hiện bằng chứng mạnh hoặc thuyết phục.' },
    { id: 'q42', skill: 'vocabulary', level: 'C1', prompt: 'Independent records _____ the witness’s account by confirming the same times and locations.', options: ['undermine', 'obscure', 'corroborate', 'retract'], correctAnswer: 2, explanation: 'Corroborate nghĩa là xác nhận hoặc củng cố một lời kể bằng bằng chứng độc lập. Các hồ sơ khớp thời gian và địa điểm nên hỗ trợ lời khai.' },
    { id: 'q43', skill: 'vocabulary', level: 'C1', prompt: 'When the editor says she “takes issue with” the conclusion, she means she _____.', options: ['disagrees with it', 'takes responsibility for publishing it', 'finds it impossible to understand', 'accepts it without reservation'], correctAnswer: 0, explanation: 'Take issue with something là phản đối hoặc không đồng tình với điều đó. Thành ngữ này không có nghĩa là nhận trách nhiệm.' },
    { id: 'q44', skill: 'grammar', level: 'C1', prompt: 'Not until the final interview _____ how limited the evidence was.', options: ['we realized', 'had we realize', 'we did realize', 'did we realize'], correctAnswer: 3, explanation: 'Khi Not until đứng đầu câu, mệnh đề chính đảo trợ động từ: did we realize. Động từ chính sau did giữ nguyên mẫu.' },
    { id: 'q45', skill: 'grammar', level: 'C1', prompt: 'I did not learn to drive when I was younger. If I had learned then, I _____ able to drive to work now.', options: ['would have been', 'would be', 'will have been', 'had been'], correctAnswer: 1, explanation: 'Đây là điều kiện hỗn hợp: giả định quá khứ if I had learned dẫn đến kết quả ở hiện tại, được đánh dấu bằng now, nên dùng would be.' },
    { id: 'q46', skill: 'reading', level: 'C1', prompt: 'Which conclusion is consistent with the passage?', passage: 'The trial suggests that a shorter working week may improve concentration. It does not follow, however, that the policy would produce the same benefit in every department. Participants volunteered, and the trial coincided with a quiet period. These limitations qualify the findings without rendering them meaningless.', options: ['The trial proves that every department should adopt the policy', 'The findings must be discarded entirely', 'The findings are promising but cannot be generalized confidently', 'Voluntary participation guarantees representative results'], correctAnswer: 2, explanation: 'Tác giả công nhận tín hiệu tích cực nhưng nêu hạn chế của mẫu tự nguyện và thời kỳ ít việc. Qualify ở đây nghĩa là giới hạn phạm vi kết luận, không phải phủ nhận toàn bộ.' },
    { id: 'q47', skill: 'reading', level: 'C1', prompt: 'How does the writer assess repair cafés?', passage: 'Repair cafés cannot reverse every decision embedded in a product’s design. Their significance lies partly in exposing those decisions: a failed repair may reveal an inaccessible component or an unavailable part. Success, therefore, should not be measured solely by the number of objects restored.', options: ['They offer value beyond successful repairs', 'They are useful only when every object is repaired', 'They remove manufacturers’ influence over repairability', 'They should stop recording unsuccessful repairs'], correctAnswer: 0, explanation: 'Tác giả cho rằng cả lần sửa thất bại cũng có giá trị vì làm rõ rào cản thiết kế. Do đó không thể chỉ đo thành công bằng số món đồ sửa được.' },
    { id: 'q48', skill: 'listening', level: 'C1', prompt: 'Under what condition would the speaker support the proposal?', audioText: 'I welcome the aim of making the service easier to use. My support for this particular proposal would depend on whether the team can demonstrate that people without smartphones will retain an equally practical way to access it. A general promise of inclusion would not be enough.', options: ['The team removes all existing access routes', 'The service becomes available only through an app', 'The team promises inclusion without testing it', 'Practical access for people without smartphones is demonstrated'], correctAnswer: 3, explanation: 'Người nói đặt điều kiện phải chứng minh người không dùng điện thoại thông minh vẫn có cách tiếp cận thuận tiện tương đương. Lời hứa chung chung không đủ.' },
    { id: 'q49', skill: 'listening', level: 'C1', prompt: 'What potential problem does the researcher emphasize?', audioText: 'The pilot reduced the workload reported by the participating team. Before celebrating, though, we should ask whether support staff quietly took over some of those tasks. A reduction on one team’s timesheet is not automatically a reduction for the organization.', options: ['Participants were unable to record their hours', 'Work may have been transferred to other employees', 'Support staff refused to participate in any project', 'The organization had no tasks left to complete'], correctAnswer: 1, explanation: 'Nhà nghiên cứu lo công việc chỉ chuyển sang nhân viên hỗ trợ. Việc một nhóm ghi nhận ít giờ hơn không tự động chứng minh cả tổ chức giảm việc.' },
    { id: 'q50', skill: 'listening', level: 'C1', prompt: 'Why does the speaker mention the comparison group?', audioText: 'The participants improved after the training, which sounds persuasive on its own. But the comparison group improved by almost the same amount without receiving the training. I am not saying nobody learned anything; I am saying we cannot attribute the entire improvement to the course.', options: ['To show that the course caused all the improvement', 'To argue that neither group improved', 'To challenge attributing all the progress to the training', 'To establish that the comparison group attended a longer course'], correctAnswer: 2, explanation: 'Nhóm so sánh cũng tiến bộ gần tương đương dù không học, nên không thể quy toàn bộ tiến bộ cho khóa đào tạo. Người nói không phủ nhận mọi việc học đã xảy ra.' },
    { id: 'q51', skill: 'vocabulary', level: 'C2', prompt: 'The spokesperson claimed to be merely asking questions, although each question smuggled in an accusation. The stance was best described as _____.', options: ['disingenuous', 'ingenuous', 'unassuming', 'forthright'], correctAnswer: 0, explanation: 'Disingenuous là thiếu thành thật, tỏ vẻ vô tư hoặc không biết trong khi cố che giấu dụng ý. Ingenuous gần nghĩa ngây thơ, chân thành; forthright là thẳng thắn.' },
    { id: 'q52', skill: 'vocabulary', level: 'C2', prompt: 'The committee’s response was deliberately _____: it could be read as either cautious approval or polite refusal.', options: ['unequivocal', 'categorical', 'unqualified', 'equivocal'], correctAnswer: 3, explanation: 'Equivocal nghĩa là mơ hồ, có thể hiểu theo nhiều hướng. Cụm either approval or refusal xác định rõ sắc thái này; ba từ còn lại đều biểu thị sự rõ ràng hoặc không dè dặt.' },
    { id: 'q53', skill: 'grammar', level: 'C2', prompt: 'The announcement went out yesterday without my approval. I would rather you _____ me before sending it.', options: ['consult', 'had consulted', 'would consult', 'have consulted'], correctAnswer: 1, explanation: 'Would rather + chủ ngữ khác + quá khứ hoàn thành diễn tả mong muốn trái với sự việc quá khứ. Thông báo đã gửi hôm qua, nên dùng had consulted.' },
    { id: 'q54', skill: 'grammar', level: 'C2', prompt: '_____ I admire the ambition of the project, I cannot endorse a budget with no provision for maintenance.', options: ['Despite that much', 'However much as', 'Much as', 'As much although'], correctAnswer: 2, explanation: 'Much as + chủ ngữ + động từ mở mệnh đề nhượng bộ, nghĩa là dù rất ngưỡng mộ. Cấu trúc này nêu sự công nhận trước khi đưa ra phản đối.' },
    { id: 'q55', skill: 'reading', level: 'C2', prompt: 'Which distinction is central to the author’s reasoning?', passage: 'The archive contains no record of an objection. That silence is compatible with unanimous approval, but also with incomplete minutes, informal dissent, or a decision never put to discussion. Treating the first possibility as established fact converts an evidential gap into a positive claim.', options: ['Compatibility with a claim is weaker than proof of that claim', 'An incomplete archive proves that everyone objected', 'Written minutes are always less reliable than informal memories', 'A claim becomes true when no alternative is recorded'], correctAnswer: 0, explanation: 'Không có hồ sơ phản đối phù hợp với khả năng mọi người đồng ý nhưng không chứng minh khả năng đó, vì còn nhiều cách giải thích khác. Tác giả phân biệt điều có thể tương thích với bằng chứng và điều được chứng minh.' },
    { id: 'q56', skill: 'reading', level: 'C2', prompt: 'What does the final sentence imply?', passage: 'The institution praised the panel for its independence. Its members had been selected by the director, its questions approved in advance, and its recommendations restricted to options the director already favored. Independence, it seemed, had been carefully protected from the inconvenience of disagreement.', options: ['The panel disagreed so strongly that it could not function', 'The director welcomed all criticism from the panel', 'The panel was independent because its remit was clear', 'The claimed independence was undermined by controls on dissent'], correctAnswer: 3, explanation: 'Câu cuối dùng mỉa mai: “bảo vệ” tính độc lập khỏi bất đồng thực chất là kiểm soát để không có phản biện. Việc chọn người, duyệt câu hỏi và giới hạn phương án làm suy yếu tính độc lập được ca ngợi.' },
    { id: 'q57', skill: 'reading', level: 'C2', prompt: 'Which claim does the passage support without going beyond its scope?', passage: 'Where repair services are accessible and replacement parts reasonably priced, consumers in the pilot were more likely to keep older appliances. The study did not compare different product categories, nor did it measure long-term energy use. Its authors accordingly framed repair access as one influence on replacement decisions, not a universal environmental verdict.', options: ['Repairing any appliance is always the most environmentally beneficial option', 'Accessible repairs were associated with keeping appliances longer in the pilot', 'The study proved that electricity use falls after every repair', 'The price of replacement parts had no relevance to participants'], correctAnswer: 1, explanation: 'Đoạn văn chỉ hỗ trợ mối liên hệ trong thử nghiệm giữa tiếp cận sửa chữa và giữ thiết bị cũ lâu hơn. Nghiên cứu không đánh giá mọi loại sản phẩm hay năng lượng dài hạn nên không cho phép kết luận môi trường tuyệt đối.' },
    { id: 'q58', skill: 'listening', level: 'C2', prompt: 'Which paraphrase best preserves the speaker’s stance?', audioText: 'I am not unsympathetic to the case for postponement. What I resist is the suggestion that postponing the decision somehow removes the need to make it. If an extension has a defined purpose and an end date, I can support it; otherwise we are merely renaming indecision.', options: ['Any postponement is unacceptable in principle', 'An indefinite delay is the best way to avoid conflict', 'A purposeful, time-limited delay is acceptable, but evasion is not', 'The decision has become unnecessary because circumstances changed'], correctAnswer: 2, explanation: 'Not unsympathetic cho thấy người nói có phần thông cảm. Họ chấp nhận gia hạn có mục đích và thời hạn cụ thể, nhưng phản đối dùng trì hoãn để né quyết định.' },
    { id: 'q59', skill: 'listening', level: 'C2', prompt: 'What flaw does the respondent identify?', audioText: 'Interviewer: No one has proved that the new process causes problems, so surely it is safe to introduce it everywhere. Respondent: That puts the burden in the wrong place. The absence of a demonstrated failure is not a demonstration that the process will work under conditions we have never tested.', options: ['Lack of evidence of failure is being treated as evidence of success', 'The process has already failed in every tested setting', 'The interviewer has confused introduction dates', 'The respondent believes successful testing is impossible'], correctAnswer: 0, explanation: 'Người trả lời chỉ ra việc lấy thiếu bằng chứng thất bại làm bằng chứng thành công. Họ không nói hệ thống chắc chắn thất bại mà yêu cầu bằng chứng phù hợp trước khi áp dụng rộng.' },
    { id: 'q60', skill: 'listening', level: 'C2', prompt: 'What is the speaker primarily objecting to?', audioText: 'It would be convenient to portray my position as hostility to reform. I helped draft the original proposal. My objection is to announcing a launch date before the staff who must deliver it have been trained. A reform can be worth pursuing and still be undermined by the manner of its introduction.', options: ['The underlying purpose of reform', 'The involvement of staff in planning', 'Any public announcement about the proposal', 'Launching the reform before adequate preparation'], correctAnswer: 3, explanation: 'Người nói ủng hộ cải cách và từng tham gia soạn đề xuất. Phản đối cụ thể là ấn định triển khai khi nhân viên chưa được đào tạo, tức cách và thời điểm thực hiện.' },
];
export const listening = [
    { id: 'l01', title: 'A new neighbor', level: 'A1', topic: 'Daily Life', duration: 1, transcript: 'Mai: Hello! Are you our new neighbor?\nBen: Yes, I am. My name is Ben. I live in apartment twelve.\nMai: Nice to meet you, Ben. I am Mai, from apartment eleven.\nBen: Nice to meet you too. Is there a supermarket near here?\nMai: Yes. There is a small supermarket next to the park. It opens at seven every morning.\nBen: Great. I need some bread and eggs for breakfast.\nMai: The bread is very good there. I usually go on Saturday morning.\nBen: Thank you for your help!\nMai: You are welcome. Enjoy your new home!', translation: 'Mai: Xin chào! Bạn là hàng xóm mới của chúng tôi phải không?\nBen: Đúng vậy. Tôi tên Ben. Tôi sống ở căn hộ số mười hai.\nMai: Rất vui được gặp bạn, Ben. Tôi là Mai, ở căn hộ số mười một.\nBen: Tôi cũng rất vui. Gần đây có siêu thị không?\nMai: Có. Có một siêu thị nhỏ cạnh công viên. Siêu thị mở cửa lúc bảy giờ mỗi sáng.\nBen: Tuyệt quá. Tôi cần ít bánh mì và trứng cho bữa sáng.\nMai: Bánh mì ở đó rất ngon. Tôi thường đi vào sáng thứ Bảy.\nBen: Cảm ơn bạn đã giúp đỡ!\nMai: Không có gì. Chúc bạn vui ở ngôi nhà mới!' },
    { id: 'l02', title: 'Changing a train ticket', level: 'A2', topic: 'Travel', duration: 1, transcript: 'Agent: Good morning. How can I help you?\nLinh: I have a ticket for the nine o’clock train to Da Nang tomorrow, but I need to travel later.\nAgent: There is another train at half past eleven. It arrives at two in the afternoon.\nLinh: That sounds good. Is a window seat available?\nAgent: Yes, seat fourteen by the window. Changing the ticket costs thirty thousand dong.\nLinh: That is fine. Can I pay by card?\nAgent: Of course. Here is your new ticket. Please arrive twenty minutes before departure.\nLinh: Thank you. I will bring just one small bag.', translation: 'Nhân viên: Chào buổi sáng. Tôi có thể giúp gì cho chị?\nLinh: Tôi có vé chuyến tàu chín giờ đi Đà Nẵng ngày mai, nhưng cần đi muộn hơn.\nNhân viên: Có một chuyến khác lúc mười một giờ rưỡi. Tàu đến lúc hai giờ chiều.\nLinh: Được đấy. Còn ghế cạnh cửa sổ không?\nNhân viên: Có, ghế số mười bốn cạnh cửa sổ. Phí đổi vé là ba mươi nghìn đồng.\nLinh: Được. Tôi có thể thanh toán bằng thẻ không?\nNhân viên: Tất nhiên. Đây là vé mới. Vui lòng đến trước giờ khởi hành hai mươi phút.\nLinh: Cảm ơn. Tôi sẽ chỉ mang một túi nhỏ.' },
    { id: 'l03', title: 'A project check-in', level: 'B1', topic: 'Work', duration: 1, transcript: 'Manager: Let us check our progress on the customer guide. Is the first draft ready?\nAn: Almost. I have written the introduction and the instructions, but I am still waiting for the product photos.\nManager: When will the design team send them?\nAn: They promised to send them on Wednesday morning. I can finish the guide by Thursday afternoon.\nManager: Our original deadline was Thursday morning. Would Friday morning give you enough time to check everything?\nAn: Yes, that would help. Could a colleague review the language as well?\nManager: Certainly. I will ask Kim to review it on Thursday. Please send her the text today.\nAn: I will. Thanks for arranging that.', translation: 'Quản lý: Chúng ta kiểm tra tiến độ hướng dẫn khách hàng nhé. Bản nháp đầu tiên đã xong chưa?\nAn: Gần xong rồi. Tôi đã viết phần giới thiệu và hướng dẫn, nhưng vẫn đang chờ ảnh sản phẩm.\nQuản lý: Khi nào nhóm thiết kế gửi ảnh?\nAn: Họ hứa gửi vào sáng thứ Tư. Tôi có thể hoàn thành tài liệu vào chiều thứ Năm.\nQuản lý: Hạn ban đầu là sáng thứ Năm. Nếu chuyển sang sáng thứ Sáu thì bạn có đủ thời gian kiểm tra mọi thứ không?\nAn: Có, như vậy sẽ tốt hơn. Một đồng nghiệp có thể kiểm tra ngôn ngữ nữa không?\nQuản lý: Chắc chắn rồi. Tôi sẽ nhờ Kim xem vào thứ Năm. Hãy gửi nội dung cho cô ấy hôm nay.\nAn: Tôi sẽ gửi. Cảm ơn đã thu xếp.' },
    { id: 'l04', title: 'Making travel more sustainable', level: 'B2', topic: 'Environment', duration: 2, transcript: 'Host: What changed the way you plan your holidays?\nGuest: I used to try to visit as many cities as possible. I would spend half the trip getting to airports and checking into hotels. Last year, I stayed in one small town for a week instead.\nHost: Did you miss having a busy itinerary?\nGuest: At first, yes. Then I discovered walking routes, local markets, and a community workshop. Staying longer made the trip more interesting and reduced the number of journeys I took.\nHost: Is that always the most affordable choice?\nGuest: Not necessarily. Train tickets can be expensive, and some destinations have limited accommodation. I compare the whole trip, including local transport and time. My aim is to make better choices where practical, rather than pretend that every trip has no environmental cost.', translation: 'Người dẫn: Điều gì đã thay đổi cách bạn lên kế hoạch nghỉ dưỡng?\nKhách mời: Trước đây tôi cố đến càng nhiều thành phố càng tốt. Tôi dành nửa chuyến đi để ra sân bay và nhận phòng khách sạn. Năm ngoái, thay vào đó tôi ở một thị trấn nhỏ suốt một tuần.\nNgười dẫn: Bạn có thấy thiếu một lịch trình bận rộn không?\nKhách mời: Ban đầu thì có. Sau đó tôi tìm thấy các tuyến đi bộ, chợ địa phương và một buổi thực hành cộng đồng. Ở lâu hơn khiến chuyến đi thú vị hơn và giảm số chặng di chuyển.\nNgười dẫn: Đó có luôn là lựa chọn ít tốn kém nhất không?\nKhách mời: Không hẳn. Vé tàu có thể đắt và một số điểm đến ít chỗ ở. Tôi so sánh cả chuyến đi, bao gồm giao thông địa phương và thời gian. Mục tiêu của tôi là chọn tốt hơn khi khả thi, thay vì giả vờ rằng mọi chuyến đi đều không gây tác động môi trường.' },
    { id: 'l05', title: 'What a pilot study can tell us', level: 'C1', topic: 'Learning', duration: 2, transcript: 'Interviewer: Your company tested a shorter working week. Were the results positive?\nResearcher: Staff reported better concentration, and the teams completed roughly the same amount of work. Those are encouraging findings, but I would be cautious about treating them as a final verdict.\nInterviewer: What limits the conclusions?\nResearcher: Participation was voluntary, so the teams may have been unusually motivated. The trial also lasted only eight weeks, during a relatively quiet period. Neither factor makes the results worthless; both affect how confidently we can generalize.\nInterviewer: What would you recommend next?\nResearcher: A longer trial with a wider range of teams, agreed measures of quality, and a comparison group. We should also examine who absorbs any work that gets displaced. A policy that benefits one group by quietly increasing another group’s workload has not necessarily improved the organization as a whole.', translation: 'Người phỏng vấn: Công ty của ông đã thử nghiệm tuần làm việc ngắn hơn. Kết quả có tích cực không?\nNhà nghiên cứu: Nhân viên cho biết tập trung tốt hơn và các nhóm hoàn thành khối lượng công việc gần như cũ. Đó là những phát hiện đáng khích lệ, nhưng tôi sẽ thận trọng khi coi chúng là kết luận cuối cùng.\nNgười phỏng vấn: Điều gì giới hạn các kết luận?\nNhà nghiên cứu: Việc tham gia là tự nguyện, nên các nhóm có thể có động lực cao hơn bình thường. Thử nghiệm cũng chỉ kéo dài tám tuần, vào thời kỳ tương đối ít việc. Không yếu tố nào làm kết quả trở nên vô giá trị; cả hai đều ảnh hưởng đến mức độ tự tin khi khái quát hóa.\nNgười phỏng vấn: Ông đề xuất bước tiếp theo là gì?\nNhà nghiên cứu: Thử nghiệm dài hơn với nhiều loại nhóm hơn, thống nhất thước đo chất lượng và có nhóm so sánh. Chúng ta cũng nên xem ai tiếp nhận phần công việc bị chuyển đi. Một chính sách có lợi cho nhóm này bằng cách âm thầm tăng việc cho nhóm khác chưa chắc đã cải thiện toàn bộ tổ chức.' },
];
export const reading = [
    { id: 'r01', title: 'A calm start to the day', level: 'A1', category: 'Daily Life', minutes: 3, body: `My name is Hoa, and I work in a small bookshop. The shop opens at nine, but my day starts at six thirty. First, I open the window and drink a glass of water. Then I make breakfast. I usually have bread, an egg, and a banana. I do not look at my phone during breakfast.

At seven thirty, I leave home and walk to a park. My friend Minh meets me there. We walk for twenty minutes and talk about our plans. The park is quiet, and we often see the same friendly dog.

After our walk, I take the bus to work. I arrive early and read a few pages of a book before the shop opens. My morning is simple, but it gives me time to think. On rainy days, I stay home a little longer and read by the window. I still enjoy a slow, quiet start.`, translation: `Tôi tên Hoa và làm việc ở một hiệu sách nhỏ. Cửa hàng mở lúc chín giờ, nhưng ngày của tôi bắt đầu lúc sáu giờ rưỡi. Đầu tiên, tôi mở cửa sổ và uống một cốc nước. Sau đó tôi làm bữa sáng. Tôi thường ăn bánh mì, một quả trứng và một quả chuối. Tôi không xem điện thoại trong bữa sáng.

Lúc bảy giờ rưỡi, tôi rời nhà và đi bộ đến công viên. Bạn tôi là Minh gặp tôi ở đó. Chúng tôi đi bộ hai mươi phút và nói chuyện về kế hoạch của mình. Công viên yên tĩnh và chúng tôi thường gặp cùng một chú chó thân thiện.

Sau khi đi bộ, tôi đi xe buýt đến chỗ làm. Tôi đến sớm và đọc vài trang sách trước giờ mở cửa. Buổi sáng của tôi đơn giản nhưng cho tôi thời gian suy nghĩ. Vào ngày mưa, tôi ở nhà lâu hơn một chút và đọc bên cửa sổ. Tôi vẫn thích một khởi đầu chậm rãi, yên tĩnh.` },
    { id: 'r02', title: 'One afternoon without a phone', level: 'A2', category: 'Daily Life', minutes: 3, body: `Last Sunday, Nam left his phone at home by accident. He noticed it when he arrived at a café, where he planned to meet his cousin. At first, he felt worried. He could not check his messages or look at the bus times. He asked the café owner for the time and ordered a glass of orange juice.

While he waited, he watched a woman draw the buildings across the street. They started talking, and she showed him her sketchbook. Nam had walked past those buildings many times, but he had never noticed their colorful doors.

His cousin arrived fifteen minutes later. They spent the afternoon walking around the neighborhood and taking turns drawing what they saw. Nam was not very good at drawing, but he enjoyed trying something new. When he returned home, he checked his messages. Nothing urgent had happened. He decided to put his phone away during his next family lunch.`, translation: `Chủ nhật tuần trước, Nam vô tình để quên điện thoại ở nhà. Anh nhận ra điều đó khi đến quán cà phê, nơi anh hẹn gặp người em họ. Ban đầu anh thấy lo. Anh không thể xem tin nhắn hay giờ xe buýt. Anh hỏi chủ quán giờ và gọi một ly nước cam.

Trong lúc chờ, anh nhìn một người phụ nữ vẽ những tòa nhà bên kia đường. Họ bắt đầu nói chuyện và cô cho anh xem sổ phác thảo. Nam đã đi qua những tòa nhà ấy nhiều lần nhưng chưa bao giờ chú ý đến các cánh cửa đầy màu sắc.

Người em họ đến sau mười lăm phút. Họ dành cả buổi chiều đi dạo quanh khu phố và thay phiên vẽ những gì nhìn thấy. Nam vẽ chưa giỏi nhưng thích thử điều mới. Khi về nhà, anh kiểm tra tin nhắn. Không có việc khẩn cấp nào xảy ra. Anh quyết định cất điện thoại đi trong bữa trưa gia đình tiếp theo.` },
    { id: 'r03', title: 'The garden between the buildings', level: 'B1', category: 'Community', minutes: 4, body: `For years, the space between two apartment buildings was used to store broken furniture. Last spring, a group of residents suggested turning it into a shared garden. Some neighbors liked the idea immediately, while others worried about noise and the cost of water.

Instead of ignoring these concerns, the organizers held a short meeting. They agreed to work only during the day, collect rainwater when possible, and publish a small monthly budget. Each volunteer chose a task that matched their time and experience. Children painted signs, older residents shared gardening advice, and several students built wooden planters.

The garden now produces herbs and a few vegetables, but food is not its greatest benefit. People who once passed each other without speaking now stop to talk. There are still disagreements about what to plant next. However, the residents have learned that a shared project does not require everyone to have the same opinion. It requires a practical way to listen and decide together.`, translation: `Trong nhiều năm, khoảng trống giữa hai tòa chung cư được dùng để chứa đồ nội thất hỏng. Mùa xuân năm ngoái, một nhóm cư dân đề xuất biến nơi đó thành vườn chung. Một số hàng xóm thích ý tưởng ngay, còn những người khác lo về tiếng ồn và chi phí nước.

Thay vì bỏ qua những lo ngại này, ban tổ chức mở một cuộc họp ngắn. Họ thống nhất chỉ làm ban ngày, hứng nước mưa khi có thể và công khai ngân sách nhỏ mỗi tháng. Mỗi tình nguyện viên chọn việc phù hợp với thời gian và kinh nghiệm. Trẻ em vẽ biển, cư dân lớn tuổi chia sẻ cách làm vườn và vài sinh viên đóng bồn trồng cây bằng gỗ.

Khu vườn hiện cho rau thơm và một ít rau củ, nhưng thực phẩm không phải lợi ích lớn nhất. Những người từng đi ngang nhau không nói gì nay dừng lại trò chuyện. Vẫn có bất đồng về loại cây sẽ trồng tiếp. Tuy nhiên, cư dân đã hiểu rằng một dự án chung không đòi hỏi mọi người cùng quan điểm. Điều cần thiết là một cách thực tế để lắng nghe và quyết định cùng nhau.` },
    { id: 'r04', title: 'Fewer meetings, clearer decisions', level: 'B2', category: 'Work', minutes: 4, body: `When a design studio reviewed its calendar, it discovered that many employees spent nearly half their working hours in meetings. The immediate response was to shorten every meeting. Although this freed some time, it did not solve the underlying problem: nobody was sure which discussions actually required a group.

The studio introduced a different rule. Every invitation had to state the decision needed, provide relevant information in advance, and identify who would make the final choice. Updates that required no discussion moved to a shared document. After each meeting, one person recorded the decision and the next action.

The change did not eliminate meetings. In fact, complex projects sometimes needed longer conversations. What improved was their purpose. Employees could prepare properly, and absent colleagues could understand the outcome. Three months later, the studio reported fewer repeated discussions. Its experience suggests that saving time begins with clearer expectations, rather than simply making every conversation shorter.`, translation: `Khi một studio thiết kế xem lại lịch, họ phát hiện nhiều nhân viên dành gần nửa giờ làm việc cho các cuộc họp. Phản ứng đầu tiên là rút ngắn mọi cuộc họp. Dù giải phóng được chút thời gian, cách này không giải quyết vấn đề cốt lõi: không ai rõ những thảo luận nào thực sự cần cả nhóm.

Studio đưa ra quy tắc khác. Mỗi lời mời phải nêu quyết định cần đưa ra, cung cấp thông tin liên quan trước và xác định ai sẽ chốt lựa chọn. Những cập nhật không cần thảo luận được chuyển sang tài liệu chung. Sau mỗi cuộc họp, một người ghi lại quyết định và hành động tiếp theo.

Thay đổi không xóa bỏ các cuộc họp. Thực tế, dự án phức tạp đôi khi cần trao đổi lâu hơn. Điều được cải thiện là mục đích họp. Nhân viên có thể chuẩn bị đầy đủ và đồng nghiệp vắng mặt có thể hiểu kết quả. Ba tháng sau, studio ghi nhận ít thảo luận lặp lại hơn. Trải nghiệm này cho thấy tiết kiệm thời gian bắt đầu từ kỳ vọng rõ ràng hơn, thay vì chỉ rút ngắn mọi cuộc trao đổi.` },
    { id: 'r05', title: 'Repair is more than a technical skill', level: 'C1', category: 'Environment', minutes: 5, body: `A neighborhood repair café may look like a collection of workbenches, but its value extends beyond the objects returned to use. Visitors bring faulty lamps, torn jackets, and appliances that manufacturers no longer support. Volunteers offer tools and guidance, usually asking owners to participate rather than simply leave an item behind.

This arrangement changes the relationship between people and their possessions. An apparently mysterious device becomes something that can be examined, understood, and sometimes fixed. Even an unsuccessful repair can reveal why a product is difficult to maintain or which replacement parts are unavailable.

Yet repair cafés cannot compensate for every design decision made upstream. A sealed casing or inaccessible component may defeat the most patient volunteer. Their broader contribution is to make these limitations visible. By turning private frustration into shared knowledge, they create informed questions about durability, access to information, and responsibility. Repair therefore offers both an immediate service and a practical way to scrutinize the systems that shape consumption.`, translation: `Một quán sửa đồ cộng đồng có thể trông như tập hợp những bàn thao tác, nhưng giá trị của nó vượt ra ngoài các món đồ được sử dụng trở lại. Khách mang đến đèn hỏng, áo rách và thiết bị mà nhà sản xuất không còn hỗ trợ. Tình nguyện viên cung cấp dụng cụ và hướng dẫn, thường đề nghị chủ đồ cùng tham gia thay vì chỉ để món đồ lại.

Cách tổ chức này thay đổi mối quan hệ giữa con người và đồ vật. Một thiết bị tưởng chừng bí ẩn trở thành thứ có thể xem xét, hiểu và đôi khi sửa được. Ngay cả lần sửa thất bại cũng có thể cho thấy vì sao sản phẩm khó bảo dưỡng hoặc linh kiện thay thế nào không có.

Tuy nhiên, quán sửa đồ không thể bù đắp mọi quyết định thiết kế từ trước. Vỏ kín hoặc linh kiện không thể tiếp cận có thể khiến cả tình nguyện viên kiên nhẫn nhất bó tay. Đóng góp rộng hơn của họ là làm rõ những giới hạn này. Bằng cách biến bực bội riêng thành kiến thức chung, họ tạo ra những câu hỏi có cơ sở về độ bền, quyền tiếp cận thông tin và trách nhiệm. Vì vậy, sửa chữa vừa cung cấp dịch vụ tức thời vừa là cách thực tế để xem xét kỹ các hệ thống định hình việc tiêu dùng.` },
];
export const vocabulary = [
    { id: 'v01', word: 'greeting', ipa: '/ˈɡriːtɪŋ/', meaning: 'lời chào', definition: 'Something you say or do when you meet someone.', partOfSpeech: 'noun', example: 'A friendly greeting can start a good conversation.', translation: 'Một lời chào thân thiện có thể mở đầu một cuộc trò chuyện tốt đẹp.', category: 'Daily Life', level: 'A1', synonyms: ['salutation', 'welcome'], antonyms: ['farewell'], collocations: ['a warm greeting', 'exchange greetings'], wordFamily: ['greet (verb)', 'greeting (noun)'] },
    { id: 'v02', word: 'neighbor', ipa: '/ˈneɪbər/', meaning: 'hàng xóm', definition: 'A person who lives near you.', partOfSpeech: 'noun', example: 'Our neighbor waters our plants when we travel.', translation: 'Hàng xóm tưới cây giúp chúng tôi khi chúng tôi đi du lịch.', category: 'Daily Life', level: 'A1', synonyms: ['nearby resident'], antonyms: [], collocations: ['next-door neighbor', 'friendly neighbor'], wordFamily: ['neighborhood (noun)', 'neighborly (adjective)'] },
    { id: 'v03', word: 'breakfast', ipa: '/ˈbrekfəst/', meaning: 'bữa sáng', definition: 'The first meal of the day.', partOfSpeech: 'noun', example: 'I usually have eggs and bread for breakfast.', translation: 'Tôi thường ăn trứng và bánh mì vào bữa sáng.', category: 'Daily Life', level: 'A1', synonyms: ['morning meal'], antonyms: [], collocations: ['have breakfast', 'skip breakfast'], wordFamily: ['breakfast (verb)'] },
    { id: 'v04', word: 'habit', ipa: '/ˈhæbɪt/', meaning: 'thói quen', definition: 'Something you do regularly, often without thinking about it.', partOfSpeech: 'noun', example: 'Reading before bed is a relaxing habit.', translation: 'Đọc sách trước khi ngủ là một thói quen giúp thư giãn.', category: 'Daily Life', level: 'A2', synonyms: ['routine', 'custom'], antonyms: [], collocations: ['develop a habit', 'break a habit'], wordFamily: ['habitual (adjective)', 'habitually (adverb)'] },
    { id: 'v05', word: 'borrow', ipa: '/ˈbɑːroʊ/', meaning: 'mượn', definition: 'To take something temporarily with the intention of returning it.', partOfSpeech: 'verb', example: 'May I borrow your umbrella until tomorrow?', translation: 'Tôi có thể mượn ô của bạn đến ngày mai không?', category: 'Daily Life', level: 'A2', synonyms: ['take on loan'], antonyms: ['lend'], collocations: ['borrow a book', 'borrow money from someone'], wordFamily: ['borrower (noun)', 'borrowing (noun)'] },
    { id: 'v06', word: 'quiet', ipa: '/ˈkwaɪət/', meaning: 'yên tĩnh', definition: 'Making very little noise.', partOfSpeech: 'adjective', example: 'The library is quiet in the morning.', translation: 'Thư viện rất yên tĩnh vào buổi sáng.', category: 'Daily Life', level: 'A1', synonyms: ['silent', 'peaceful'], antonyms: ['noisy', 'loud'], collocations: ['a quiet room', 'keep quiet'], wordFamily: ['quietly (adverb)', 'quietness (noun)'] },
    { id: 'v07', word: 'appointment', ipa: '/əˈpɔɪntmənt/', meaning: 'cuộc hẹn', definition: 'An arrangement to meet someone at a particular time.', partOfSpeech: 'noun', example: 'I have a dentist appointment at ten.', translation: 'Tôi có cuộc hẹn với nha sĩ lúc mười giờ.', category: 'Daily Life', level: 'A2', synonyms: ['scheduled meeting'], antonyms: [], collocations: ['make an appointment', 'cancel an appointment'], wordFamily: ['appoint (verb)', 'appointed (adjective)'] },
    { id: 'v08', word: 'receipt', ipa: '/rɪˈsiːt/', meaning: 'biên lai; hóa đơn thanh toán', definition: 'A document showing that you have paid for something.', partOfSpeech: 'noun', example: 'Keep the receipt in case you need to return the jacket.', translation: 'Hãy giữ biên lai phòng khi bạn cần trả lại áo khoác.', category: 'Daily Life', level: 'A2', synonyms: ['proof of payment'], antonyms: [], collocations: ['keep a receipt', 'ask for a receipt'], wordFamily: ['receive (verb)', 'receivable (adjective)'] },
    { id: 'v09', word: 'ingredient', ipa: '/ɪnˈɡriːdiənt/', meaning: 'nguyên liệu; thành phần', definition: 'One of the foods or substances used to make a dish or product.', partOfSpeech: 'noun', example: 'Fresh ginger is an important ingredient in this soup.', translation: 'Gừng tươi là một nguyên liệu quan trọng trong món súp này.', category: 'Daily Life', level: 'A2', synonyms: ['component', 'constituent'], antonyms: [], collocations: ['fresh ingredients', 'a key ingredient'], wordFamily: ['ingredient (noun)'] },
    { id: 'v10', word: 'crowded', ipa: '/ˈkraʊdɪd/', meaning: 'đông đúc', definition: 'Full of people, leaving little space to move.', partOfSpeech: 'adjective', example: 'The market becomes crowded before the holiday.', translation: 'Chợ trở nên đông đúc trước kỳ nghỉ lễ.', category: 'Daily Life', level: 'A2', synonyms: ['packed', 'busy'], antonyms: ['empty', 'uncrowded'], collocations: ['a crowded bus', 'a crowded street'], wordFamily: ['crowd (noun/verb)', 'overcrowded (adjective)'] },
    { id: 'v11', word: 'commute', ipa: '/kəˈmjuːt/', meaning: 'đi lại hằng ngày giữa nhà và nơi làm việc', definition: 'To travel regularly between your home and your place of work.', partOfSpeech: 'verb', example: 'She commutes to the office by train.', translation: 'Cô ấy đi tàu từ nhà đến văn phòng hằng ngày.', category: 'Work', level: 'B1', synonyms: ['travel to work'], antonyms: [], collocations: ['commute by train', 'a daily commute'], wordFamily: ['commuter (noun)', 'commuting (noun)'] },
    { id: 'v12', word: 'deadline', ipa: '/ˈdedlaɪn/', meaning: 'hạn chót', definition: 'The latest time or date by which something must be completed.', partOfSpeech: 'noun', example: 'The deadline for the report is Friday afternoon.', translation: 'Hạn chót nộp báo cáo là chiều thứ Sáu.', category: 'Work', level: 'B1', synonyms: ['due date', 'time limit'], antonyms: [], collocations: ['meet a deadline', 'miss a deadline'], wordFamily: ['deadline (noun)'] },
    { id: 'v13', word: 'colleague', ipa: '/ˈkɑːliːɡ/', meaning: 'đồng nghiệp', definition: 'A person you work with.', partOfSpeech: 'noun', example: 'My colleague helped me prepare the presentation.', translation: 'Đồng nghiệp đã giúp tôi chuẩn bị bài thuyết trình.', category: 'Work', level: 'A2', synonyms: ['coworker', 'workmate'], antonyms: [], collocations: ['a close colleague', 'a former colleague'], wordFamily: ['collegial (adjective)', 'collegiality (noun)'] },
    { id: 'v14', word: 'meeting', ipa: '/ˈmiːtɪŋ/', meaning: 'cuộc họp', definition: 'An occasion when people come together to discuss something.', partOfSpeech: 'noun', example: 'Our team meeting starts at nine.', translation: 'Cuộc họp nhóm của chúng tôi bắt đầu lúc chín giờ.', category: 'Work', level: 'A1', synonyms: ['discussion', 'conference'], antonyms: [], collocations: ['attend a meeting', 'hold a meeting'], wordFamily: ['meet (verb)', 'meeting (noun)'] },
    { id: 'v15', word: 'schedule', ipa: '/ˈskedʒuːl/', meaning: 'lịch trình', definition: 'A plan that lists activities and the times when they will happen.', partOfSpeech: 'noun', example: 'Please check the schedule before booking your train.', translation: 'Vui lòng kiểm tra lịch trình trước khi đặt vé tàu.', category: 'Work', level: 'A2', synonyms: ['timetable', 'agenda'], antonyms: [], collocations: ['a busy schedule', 'ahead of schedule'], wordFamily: ['schedule (verb)', 'reschedule (verb)', 'scheduled (adjective)'] },
    { id: 'v16', word: 'improve', ipa: '/ɪmˈpruːv/', meaning: 'cải thiện', definition: 'To become better or make something better.', partOfSpeech: 'verb', example: 'Daily practice will improve your pronunciation.', translation: 'Luyện tập hằng ngày sẽ cải thiện phát âm của bạn.', category: 'Learning', level: 'A2', synonyms: ['enhance', 'develop'], antonyms: ['worsen', 'deteriorate'], collocations: ['improve your skills', 'improve steadily'], wordFamily: ['improvement (noun)', 'improved (adjective)'] },
    { id: 'v17', word: 'reliable', ipa: '/rɪˈlaɪəbəl/', meaning: 'đáng tin cậy', definition: 'Able to be trusted to work well or do what is expected.', partOfSpeech: 'adjective', example: 'We need a reliable supplier for the new project.', translation: 'Chúng tôi cần một nhà cung cấp đáng tin cậy cho dự án mới.', category: 'Work', level: 'B1', synonyms: ['dependable', 'trustworthy'], antonyms: ['unreliable'], collocations: ['a reliable source', 'highly reliable'], wordFamily: ['rely (verb)', 'reliability (noun)', 'reliably (adverb)'] },
    { id: 'v18', word: 'feedback', ipa: '/ˈfiːdbæk/', meaning: 'ý kiến phản hồi', definition: 'Information about someone’s work that helps them understand its quality.', partOfSpeech: 'noun', example: 'The teacher gave us helpful feedback on our essays.', translation: 'Giáo viên cho chúng tôi những nhận xét hữu ích về bài luận.', category: 'Work', level: 'B1', synonyms: ['comments', 'evaluation'], antonyms: [], collocations: ['constructive feedback', 'give feedback'], wordFamily: ['feed back (phrasal verb)'] },
    { id: 'v19', word: 'itinerary', ipa: '/aɪˈtɪnəreri/', meaning: 'lịch trình chuyến đi', definition: 'A detailed plan of a journey, including places and dates.', partOfSpeech: 'noun', example: 'Our itinerary includes two days in Hue.', translation: 'Lịch trình của chúng tôi có hai ngày ở Huế.', category: 'Travel', level: 'B2', synonyms: ['travel plan', 'route plan'], antonyms: [], collocations: ['a detailed itinerary', 'plan an itinerary'], wordFamily: ['itinerary (noun)'] },
    { id: 'v20', word: 'destination', ipa: '/ˌdestɪˈneɪʃən/', meaning: 'điểm đến', definition: 'The place to which someone or something is going.', partOfSpeech: 'noun', example: 'Da Nang is our final destination.', translation: 'Đà Nẵng là điểm đến cuối cùng của chúng tôi.', category: 'Travel', level: 'A2', synonyms: ['endpoint', 'arrival point'], antonyms: ['starting point', 'origin'], collocations: ['a popular destination', 'reach your destination'], wordFamily: ['destined (adjective)'] },
    { id: 'v21', word: 'accommodation', ipa: '/əˌkɑːməˈdeɪʃən/', meaning: 'chỗ ở', definition: 'A place to stay, especially during a trip.', partOfSpeech: 'noun', example: 'We booked accommodation near the old town.', translation: 'Chúng tôi đã đặt chỗ ở gần phố cổ.', category: 'Travel', level: 'B1', synonyms: ['lodging', 'a place to stay'], antonyms: [], collocations: ['book accommodation', 'affordable accommodation'], wordFamily: ['accommodate (verb)'] },
    { id: 'v22', word: 'luggage', ipa: '/ˈlʌɡɪdʒ/', meaning: 'hành lý', definition: 'The bags and suitcases that you take when traveling.', partOfSpeech: 'noun', example: 'Please keep your luggage with you at the station.', translation: 'Vui lòng giữ hành lý bên mình tại nhà ga.', category: 'Travel', level: 'A2', synonyms: ['baggage'], antonyms: [], collocations: ['hand luggage', 'a piece of luggage'], wordFamily: ['luggage (uncountable noun)'] },
    { id: 'v23', word: 'departure', ipa: '/dɪˈpɑːrtʃər/', meaning: 'sự khởi hành; giờ khởi hành', definition: 'The act or time of leaving a place.', partOfSpeech: 'noun', example: 'Boarding begins thirty minutes before departure.', translation: 'Việc lên máy bay bắt đầu ba mươi phút trước giờ khởi hành.', category: 'Travel', level: 'B1', synonyms: ['leaving', 'setting off'], antonyms: ['arrival'], collocations: ['departure time', 'departure lounge'], wordFamily: ['depart (verb)', 'departing (adjective)'] },
    { id: 'v24', word: 'explore', ipa: '/ɪkˈsplɔːr/', meaning: 'khám phá', definition: 'To travel around a place or examine a subject to learn about it.', partOfSpeech: 'verb', example: 'We spent the afternoon exploring the village.', translation: 'Chúng tôi dành buổi chiều khám phá ngôi làng.', category: 'Travel', level: 'B1', synonyms: ['investigate', 'discover'], antonyms: [], collocations: ['explore a city', 'explore the possibilities'], wordFamily: ['explorer (noun)', 'exploration (noun)', 'exploratory (adjective)'] },
    { id: 'v25', word: 'sustainable', ipa: '/səˈsteɪnəbəl/', meaning: 'bền vững', definition: 'Able to continue over time without using up resources or causing lasting harm.', partOfSpeech: 'adjective', example: 'The city is investing in sustainable transport.', translation: 'Thành phố đang đầu tư vào giao thông bền vững.', category: 'Environment', level: 'B2', synonyms: ['viable', 'maintainable'], antonyms: ['unsustainable'], collocations: ['sustainable development', 'a sustainable future'], wordFamily: ['sustain (verb)', 'sustainability (noun)', 'sustainably (adverb)'] },
    { id: 'v26', word: 'reduce', ipa: '/rɪˈduːs/', meaning: 'giảm; cắt giảm', definition: 'To make something smaller in amount, size, or degree.', partOfSpeech: 'verb', example: 'Taking the bus can reduce travel costs.', translation: 'Đi xe buýt có thể giảm chi phí đi lại.', category: 'Environment', level: 'B1', synonyms: ['decrease', 'lower'], antonyms: ['increase', 'raise'], collocations: ['reduce waste', 'reduce costs'], wordFamily: ['reduction (noun)', 'reduced (adjective)'] },
    { id: 'v27', word: 'benefit', ipa: '/ˈbenɪfɪt/', meaning: 'lợi ích', definition: 'A helpful or positive effect of something.', partOfSpeech: 'noun', example: 'One benefit of walking is that it costs nothing.', translation: 'Một lợi ích của việc đi bộ là không tốn tiền.', category: 'Learning', level: 'B1', synonyms: ['advantage', 'gain'], antonyms: ['drawback', 'disadvantage'], collocations: ['a major benefit', 'bring benefits'], wordFamily: ['benefit (verb)', 'beneficial (adjective)', 'beneficiary (noun)'] },
    { id: 'v28', word: 'challenge', ipa: '/ˈtʃælɪndʒ/', meaning: 'thử thách', definition: 'A difficult task or situation that tests your ability.', partOfSpeech: 'noun', example: 'Speaking to a large audience was a new challenge.', translation: 'Nói trước đông người là một thử thách mới.', category: 'Learning', level: 'B1', synonyms: ['test', 'difficulty'], antonyms: [], collocations: ['face a challenge', 'overcome a challenge'], wordFamily: ['challenge (verb)', 'challenging (adjective)', 'challenger (noun)'] },
    { id: 'v29', word: 'opportunity', ipa: '/ˌɑːpərˈtuːnəti/', meaning: 'cơ hội', definition: 'A situation that makes it possible to do something useful or desirable.', partOfSpeech: 'noun', example: 'The workshop is an opportunity to meet other designers.', translation: 'Buổi hội thảo là cơ hội gặp gỡ các nhà thiết kế khác.', category: 'Work', level: 'B1', synonyms: ['chance', 'opening'], antonyms: [], collocations: ['a valuable opportunity', 'take an opportunity'], wordFamily: ['opportune (adjective)', 'opportunistic (adjective)'] },
    { id: 'v30', word: 'achieve', ipa: '/əˈtʃiːv/', meaning: 'đạt được', definition: 'To succeed in doing or getting something through effort.', partOfSpeech: 'verb', example: 'Small daily steps help you achieve your goals.', translation: 'Những bước nhỏ mỗi ngày giúp bạn đạt được mục tiêu.', category: 'Learning', level: 'B1', synonyms: ['accomplish', 'attain'], antonyms: ['fail to attain'], collocations: ['achieve a goal', 'achieve success'], wordFamily: ['achievement (noun)', 'achievable (adjective)', 'achiever (noun)'] },
    { id: 'v31', word: 'negotiate', ipa: '/nɪˈɡoʊʃieɪt/', meaning: 'đàm phán; thương lượng', definition: 'To discuss something formally in order to reach an agreement.', partOfSpeech: 'verb', example: 'We negotiated a better price with the supplier.', translation: 'Chúng tôi đã thương lượng được mức giá tốt hơn với nhà cung cấp.', category: 'Work', level: 'B2', synonyms: ['bargain', 'discuss terms'], antonyms: [], collocations: ['negotiate a contract', 'negotiate with a supplier'], wordFamily: ['negotiation (noun)', 'negotiator (noun)', 'negotiable (adjective)'] },
    { id: 'v32', word: 'efficient', ipa: '/ɪˈfɪʃənt/', meaning: 'hiệu quả; ít lãng phí nguồn lực', definition: 'Working well without wasting time, energy, or materials.', partOfSpeech: 'adjective', example: 'An efficient booking system saves staff time.', translation: 'Một hệ thống đặt chỗ hiệu quả giúp nhân viên tiết kiệm thời gian.', category: 'Work', level: 'B2', synonyms: ['well-organized', 'productive'], antonyms: ['inefficient', 'wasteful'], collocations: ['energy efficient', 'an efficient process'], wordFamily: ['efficiency (noun)', 'efficiently (adverb)', 'inefficiency (noun)'] },
    { id: 'v33', word: 'perspective', ipa: '/pərˈspektɪv/', meaning: 'góc nhìn; quan điểm', definition: 'A particular way of thinking about or seeing something.', partOfSpeech: 'noun', example: 'Listening to customers gave us a different perspective.', translation: 'Lắng nghe khách hàng giúp chúng tôi có một góc nhìn khác.', category: 'Learning', level: 'B2', synonyms: ['viewpoint', 'outlook'], antonyms: [], collocations: ['a fresh perspective', 'from my perspective'], wordFamily: ['perspective (noun)', 'perspectival (adjective)'] },
    { id: 'v34', word: 'evidence', ipa: '/ˈevɪdəns/', meaning: 'bằng chứng', definition: 'Facts or information that help show whether something is true.', partOfSpeech: 'noun', example: 'The team collected evidence before changing its plan.', translation: 'Nhóm đã thu thập bằng chứng trước khi thay đổi kế hoạch.', category: 'Learning', level: 'B2', synonyms: ['supporting information', 'proof'], antonyms: [], collocations: ['strong evidence', 'provide evidence'], wordFamily: ['evident (adjective)', 'evidently (adverb)', 'evidential (adjective)'] },
    { id: 'v35', word: 'compromise', ipa: '/ˈkɑːmprəmaɪz/', meaning: 'sự thỏa hiệp', definition: 'An agreement in which each side accepts less than it originally wanted.', partOfSpeech: 'noun', example: 'We reached a compromise on the delivery date.', translation: 'Chúng tôi đã đạt được thỏa hiệp về ngày giao hàng.', category: 'Work', level: 'B2', synonyms: ['middle ground', 'settlement'], antonyms: ['deadlock'], collocations: ['reach a compromise', 'a reasonable compromise'], wordFamily: ['compromise (verb)', 'uncompromising (adjective)'] },
    { id: 'v36', word: 'resilient', ipa: '/rɪˈzɪliənt/', meaning: 'kiên cường; có khả năng phục hồi', definition: 'Able to recover and adapt after difficulty or change.', partOfSpeech: 'adjective', example: 'The resilient team learned from the setback and tried again.', translation: 'Nhóm kiên cường đã rút kinh nghiệm từ thất bại và thử lại.', category: 'Learning', level: 'B2', synonyms: ['adaptable', 'tough'], antonyms: ['fragile', 'vulnerable'], collocations: ['remain resilient', 'a resilient community'], wordFamily: ['resilience (noun)', 'resiliently (adverb)'] },
];
export const grammar = [
    { id: 'g01', title: 'Động từ to be', level: 'A1', description: 'Giới thiệu bản thân, mô tả người và nói về vị trí với am, is, are.', structure: ['I + am + noun/adjective.', 'He/She/It + is + noun/adjective.', 'You/We/They + are + noun/adjective.', 'Am/Is/Are + subject + complement?'], examples: ['I am a student.', 'She is from Vietnam.', 'Are they at home?'], notes: 'Dùng not ngay sau be để phủ định. Trong câu hỏi, đưa be lên trước chủ ngữ.', commonMistake: 'Sai: She are happy. Đúng: She is happy. Chủ ngữ she đi với is.' },
    { id: 'g02', title: 'Hiện tại đơn', level: 'A1', description: 'Nói về thói quen, lịch trình và sự thật thường xuyên đúng.', structure: ['I/You/We/They + base verb.', 'He/She/It + verb-s/es.', 'Subject + do/does not + base verb.', 'Do/Does + subject + base verb?'], examples: ['I read every evening.', 'Lan works at a bank.', 'Does he live near here?'], notes: 'Sau does hoặc does not, động từ chính trở về nguyên mẫu. Trạng từ tần suất thường đứng trước động từ thường.', commonMistake: 'Sai: Does she likes tea? Đúng: Does she like tea?' },
    { id: 'g03', title: 'Hiện tại tiếp diễn', level: 'A1', description: 'Mô tả hành động đang xảy ra hoặc một tình huống tạm thời.', structure: ['Subject + am/is/are + verb-ing.', 'Subject + am/is/are not + verb-ing.', 'Am/Is/Are + subject + verb-ing?'], examples: ['I am studying now.', 'They are staying with friends this week.', 'What are you cooking?'], notes: 'Các động từ chỉ trạng thái như know và believe thường không dùng ở tiếp diễn trong nghĩa chỉ trạng thái.', commonMistake: 'Sai: I am knowing the answer. Đúng: I know the answer.' },
    { id: 'g04', title: 'Mạo từ a, an và the', level: 'A1', description: 'Phân biệt một đối tượng chưa xác định với đối tượng người nghe có thể nhận biết.', structure: ['a + singular countable noun starting with a consonant sound', 'an + singular countable noun starting with a vowel sound', 'the + identifiable noun'], examples: ['I bought a book. The book is about travel.', 'She is an engineer.', 'He studies at a university.'], notes: 'Chọn a/an dựa vào âm đầu, không chỉ chữ cái: an hour nhưng a university. Danh từ số nhiều nói chung thường không cần mạo từ.', commonMistake: 'Sai: an university. Đúng: a university vì university bắt đầu bằng âm /j/.' },
    { id: 'g05', title: 'Danh từ đếm được và lượng từ', level: 'A2', description: 'Dùng some, any, much, many, a few và a little theo loại danh từ.', structure: ['many / a few + plural countable noun', 'much / a little + uncountable noun', 'some / any + plural countable or uncountable noun'], examples: ['We have a few apples.', 'There is a little milk left.', 'How much luggage do you have?'], notes: 'Luggage, advice và information là danh từ không đếm được trong cách dùng thông thường. Some cũng dùng trong lời mời hoặc đề nghị khi mong đợi câu trả lời đồng ý.', commonMistake: 'Sai: two advices. Đúng: two pieces of advice.' },
    { id: 'g06', title: 'Quá khứ đơn', level: 'A2', description: 'Kể về sự việc đã kết thúc tại một thời điểm trong quá khứ.', structure: ['Subject + past verb.', 'Subject + did not + base verb.', 'Did + subject + base verb?'], examples: ['We visited Hue last summer.', 'She went home early.', 'Did you see the exhibition?'], notes: 'Động từ có quy tắc thêm -ed; động từ bất quy tắc cần học riêng. Với be, dùng was/were và không dùng did.', commonMistake: 'Sai: Did you went? Đúng: Did you go?' },
    { id: 'g07', title: 'Will, be going to và kế hoạch tương lai', level: 'A2', description: 'Diễn đạt quyết định tức thời, dự định và dự đoán.', structure: ['Subject + will + base verb.', 'Subject + am/is/are going to + base verb.', 'Subject + am/is/are + verb-ing + future time.'], examples: ['The phone is ringing. I will answer it.', 'We are going to visit our grandparents.', 'I am meeting Hoa at six tomorrow.'], notes: 'Going to thường diễn tả dự định có trước hoặc dự đoán dựa vào dấu hiệu hiện tại. Hiện tại tiếp diễn có thể diễn tả một sắp xếp đã được xác nhận.', commonMistake: 'Sai: She will to call. Đúng: She will call.' },
    { id: 'g08', title: 'So sánh hơn và so sánh nhất', level: 'A2', description: 'So sánh hai đối tượng hoặc xác định một đối tượng nổi bật trong nhóm.', structure: ['short adjective-er + than', 'more + longer adjective + than', 'the + short adjective-est', 'the most + longer adjective', 'as + adjective + as'], examples: ['This room is quieter than that one.', 'The train is more comfortable than the bus.', 'It is the best option for us.'], notes: 'Good → better → best; bad → worse → worst. Không dùng đồng thời more với dạng -er.', commonMistake: 'Sai: more cheaper. Đúng: cheaper.' },
    { id: 'g09', title: 'Động từ khuyết thiếu', level: 'A2', description: 'Diễn đạt khả năng, lời khuyên, nghĩa vụ và sự cho phép.', structure: ['Subject + can/could/should/must + base verb.', 'Subject + must not + base verb.', 'Subject + do/does not have to + base verb.'], examples: ['You should check the address.', 'Visitors must not enter this room.', 'You do not have to bring lunch; we provide it.'], notes: 'Must not là bị cấm; do not have to là không bắt buộc. Động từ sau modal không thêm -s và không có to.', commonMistake: 'Nhầm must not với do not have to. You must not pay nghĩa là bạn không được trả, không phải bạn không cần trả.' },
    { id: 'g10', title: 'Hiện tại hoàn thành', level: 'B1', description: 'Liên hệ một trải nghiệm hoặc sự việc quá khứ với hiện tại.', structure: ['Subject + have/has + past participle.', 'Subject + have/has not + past participle.', 'Have/Has + subject + past participle?'], examples: ['I have visited Hoi An twice.', 'She has worked here since 2022.', 'We have not finished the report yet.'], notes: 'Since + mốc bắt đầu; for + khoảng thời gian. Khi nêu thời điểm quá khứ đã kết thúc như yesterday, thường dùng quá khứ đơn.', commonMistake: 'Sai: I have seen him yesterday. Đúng: I saw him yesterday.' },
    { id: 'g11', title: 'Điều kiện loại 1 và loại 2', level: 'B1', description: 'Phân biệt khả năng thực tế trong tương lai với tình huống giả định.', structure: ['If + present simple, subject + will + base verb.', 'If + past simple, subject + would + base verb.'], examples: ['If it rains, we will stay inside.', 'If I had more time, I would learn Korean.', 'If I were you, I would ask for feedback.'], notes: 'Loại 2 dùng dạng quá khứ để tạo khoảng cách với thực tế, không nhất thiết nói về thời gian quá khứ. Were phổ biến trong giả định trang trọng.', commonMistake: 'Sai trong dự đoán thông thường: If it will rain, we will stay home. Đúng: If it rains, we will stay home.' },
    { id: 'g12', title: 'Mệnh đề quan hệ', level: 'B1', description: 'Bổ sung thông tin về người, vật hoặc nơi chốn.', structure: ['person + who/that + clause', 'thing + which/that + clause', 'place + where + clause', 'noun, who/which + non-defining clause, ...'], examples: ['The colleague who helped me is on leave.', 'This is the hotel where we stayed.', 'My bike, which is ten years old, still works well.'], notes: 'Mệnh đề không xác định được ngăn bằng dấu phẩy và không dùng that. Có thể lược đại từ quan hệ làm tân ngữ trong mệnh đề xác định.', commonMistake: 'Sai: My sister, that lives in Hue, is a teacher. Đúng: My sister, who lives in Hue, is a teacher.' },
    { id: 'g13', title: 'Câu bị động', level: 'B1', description: 'Tập trung vào đối tượng chịu tác động khi tác nhân không quan trọng hoặc chưa rõ.', structure: ['Subject + be in the required tense + past participle.', 'Subject + modal + be + past participle.', 'Subject + have/has been + past participle.'], examples: ['The rooms are cleaned every day.', 'The bridge was built in 1998.', 'The form must be submitted today.'], notes: 'Giữ nguyên thì bằng cách chia be. Có thể thêm by + tác nhân khi thông tin này cần thiết.', commonMistake: 'Sai: The email was send yesterday. Đúng: The email was sent yesterday.' },
    { id: 'g14', title: 'Câu tường thuật', level: 'B2', description: 'Thuật lại lời nói, câu hỏi và yêu cầu trong một ngữ cảnh mới.', structure: ['said (that) + clause', 'told + person + clause', 'asked + person + if/whether + subject + verb', 'asked/told + person + to + base verb'], examples: ['She said that she was busy.', 'He asked whether I had finished.', 'They told us to wait outside.'], notes: 'Khi động từ tường thuật ở quá khứ, thường lùi thì nếu góc nhìn thời gian đã thay đổi. Không nhất thiết lùi thì khi sự thật vẫn còn đúng. Câu hỏi gián tiếp dùng trật tự câu trần thuật.', commonMistake: 'Sai: He asked where did I live. Đúng: He asked where I lived.' },
    { id: 'g15', title: 'Quá khứ hoàn thành và điều kiện loại 3', level: 'B2', description: 'Làm rõ thứ tự sự kiện quá khứ và hình dung kết quả khác của điều đã xảy ra.', structure: ['Subject + had + past participle.', 'If + subject + had + past participle, subject + would have + past participle.'], examples: ['The train had left when we arrived.', 'If I had checked the map, I would not have got lost.', 'She had never flown before that trip.'], notes: 'Quá khứ hoàn thành mô tả sự việc trước một mốc quá khứ khác. Điều kiện loại 3 nói về giả định trái với quá khứ.', commonMistake: 'Sai: If I would have known, I would have helped. Đúng: If I had known, I would have helped.' },
    { id: 'g16', title: 'Đảo ngữ để nhấn mạnh', level: 'C1', description: 'Dùng đảo trợ động từ sau trạng ngữ phủ định hoặc giới hạn đặt đầu câu.', structure: ['Never/Rarely + auxiliary + subject + main verb.', 'Not until + time/clause + auxiliary + subject + main verb.', 'No sooner + had + subject + past participle + than + clause.'], examples: ['Rarely have I seen such careful planning.', 'Not until Monday did we receive the results.', 'No sooner had we arrived than the meeting began.'], notes: 'Đảo ngữ xảy ra ở mệnh đề chính sau not until, không ở mệnh đề theo sau until. Nếu chưa có trợ động từ, dùng do/does/did phù hợp.', commonMistake: 'Sai: Not until did he arrive we started. Đúng: Not until he arrived did we start.' },
    { id: 'g17', title: 'Giả định trang trọng và khoảng cách thời gian', level: 'C2', description: 'Diễn đạt yêu cầu trang trọng và phân biệt mong muốn về hiện tại với nuối tiếc về quá khứ.', structure: ['It is essential that + subject + base verb.', 'Subject + would rather + other subject + past simple (present/future).', 'Subject + would rather + other subject + had + past participle (past).'], examples: ['It is essential that every application be reviewed.', 'I would rather you spoke to her directly tomorrow.', 'I would rather you had told me before the announcement.'], notes: 'Trong giả định yêu cầu, động từ giữ nguyên mẫu kể cả với he/she; be không đổi thành is. Cấu trúc should + nguyên mẫu cũng thường dùng trong tiếng Anh Anh. Sau would rather với chủ ngữ khác, quá khứ đơn thường chỉ hiện tại/tương lai, còn quá khứ hoàn thành chỉ quá khứ.', commonMistake: 'Sai khi nói về việc đã xảy ra hôm qua: I would rather you tell me yesterday. Đúng: I would rather you had told me yesterday.' },
];
