// Compact CEFR lexicon pack. The tuple format keeps a large seed library easy to review.
type LexiconEntry = [word: string, meaning: string, partOfSpeech: string, level: string, collocation: string];
type LexiconGroup = { category: string; entries: LexiconEntry[] };

const groups: LexiconGroup[] = [
  { category: "Daily Life", entries: [
    ["alarm", "đồng hồ báo thức", "noun", "A1", "set an alarm"], ["shower", "vòi sen; tắm vòi sen", "noun", "A1", "take a shower"],
    ["toothbrush", "bàn chải đánh răng", "noun", "A1", "new toothbrush"], ["towel", "khăn tắm", "noun", "A1", "clean towel"],
    ["laundry", "quần áo cần giặt", "noun", "A2", "do the laundry"], ["grocery", "hàng tạp hóa", "noun", "A2", "grocery store"],
    ["errand", "việc vặt", "noun", "B1", "run an errand"], ["nap", "giấc ngủ ngắn", "noun", "A2", "take a nap"],
    ["calendar", "lịch", "noun", "A1", "check the calendar"], ["weekend", "cuối tuần", "noun", "A1", "at the weekend"],
    ["weekday", "ngày trong tuần", "noun", "A2", "on weekdays"], ["doorway", "lối ra vào", "noun", "A2", "stand in the doorway"],
    ["elevator", "thang máy", "noun", "A1", "take the elevator"], ["staircase", "cầu thang", "noun", "A2", "climb the staircase"],
    ["key", "chìa khóa", "noun", "A1", "house key"], ["wallet", "ví tiền", "noun", "A1", "lose a wallet"],
    ["umbrella", "ô; dù", "noun", "A1", "carry an umbrella"], ["queue", "hàng người chờ", "noun", "A2", "join the queue"],
    ["parcel", "bưu kiện", "noun", "A2", "deliver a parcel"], ["chore", "việc nhà", "noun", "B1", "household chore"],
  ]},
  { category: "Food & Cooking", entries: [
    ["beverage", "đồ uống", "noun", "B1", "hot beverage"], ["snack", "đồ ăn nhẹ", "noun", "A1", "healthy snack"],
    ["dessert", "món tráng miệng", "noun", "A1", "order dessert"], ["recipe", "công thức nấu ăn", "noun", "A2", "follow a recipe"],
    ["flavor", "hương vị", "noun", "A2", "rich flavor"], ["spicy", "cay", "adjective", "A1", "spicy food"],
    ["sweet", "ngọt", "adjective", "A1", "sweet taste"], ["sour", "chua", "adjective", "A2", "taste sour"],
    ["bitter", "đắng", "adjective", "A2", "bitter coffee"], ["salty", "mặn", "adjective", "A2", "salty soup"],
    ["boil", "luộc; đun sôi", "verb", "A2", "boil water"], ["fry", "chiên; rán", "verb", "A2", "fry an egg"],
    ["bake", "nướng bằng lò", "verb", "A2", "bake bread"], ["chop", "băm; thái", "verb", "A2", "chop vegetables"],
    ["pour", "rót", "verb", "A2", "pour a drink"], ["serve", "phục vụ", "verb", "A2", "serve a meal"],
    ["fresh", "tươi", "adjective", "A1", "fresh fruit"], ["ripe", "chín", "adjective", "A2", "ripe banana"],
    ["portion", "khẩu phần", "noun", "B1", "small portion"], ["appetite", "sự thèm ăn", "noun", "B1", "lose your appetite"],
  ]},
  { category: "Travel", entries: [
    ["journey", "hành trình", "noun", "A2", "long journey"], ["trip", "chuyến đi", "noun", "A1", "business trip"],
    ["tourist", "khách du lịch", "noun", "A1", "foreign tourist"], ["guide", "hướng dẫn viên; hướng dẫn", "noun", "A2", "tour guide"],
    ["map", "bản đồ", "noun", "A1", "read a map"], ["ticket", "vé", "noun", "A1", "buy a ticket"],
    ["suitcase", "va li", "noun", "A1", "pack a suitcase"], ["airport", "sân bay", "noun", "A1", "international airport"],
    ["station", "nhà ga", "noun", "A1", "train station"], ["harbor", "bến cảng", "noun", "B1", "busy harbor"],
    ["vehicle", "phương tiện", "noun", "B1", "electric vehicle"], ["traffic", "giao thông", "noun", "A2", "heavy traffic"],
    ["border", "biên giới", "noun", "B1", "cross the border"], ["visa", "thị thực", "noun", "A2", "apply for a visa"],
    ["souvenir", "quà lưu niệm", "noun", "A2", "buy a souvenir"], ["abroad", "ở nước ngoài", "adverb", "A2", "study abroad"],
    ["local", "địa phương", "adjective", "A2", "local people"], ["arrive", "đến nơi", "verb", "A1", "arrive on time"],
    ["return", "trở về; trả lại", "verb", "A2", "return home"], ["wander", "đi lang thang", "verb", "B1", "wander around"],
  ]},
  { category: "Work", entries: [
    ["employee", "nhân viên", "noun", "A2", "full-time employee"], ["employer", "nhà tuyển dụng", "noun", "B1", "potential employer"],
    ["manager", "quản lý", "noun", "A2", "project manager"], ["client", "khách hàng", "noun", "B1", "meet a client"],
    ["project", "dự án", "noun", "A2", "manage a project"], ["task", "nhiệm vụ", "noun", "A2", "complete a task"],
    ["target", "mục tiêu", "noun", "B1", "meet a target"], ["report", "báo cáo", "noun", "A2", "write a report"],
    ["contract", "hợp đồng", "noun", "B1", "sign a contract"], ["application", "đơn ứng tuyển", "noun", "B1", "job application"],
    ["promotion", "sự thăng chức", "noun", "B1", "get a promotion"], ["department", "phòng ban", "noun", "A2", "sales department"],
    ["office", "văn phòng", "noun", "A1", "head office"], ["remote", "từ xa", "adjective", "B1", "remote work"],
    ["productive", "năng suất", "adjective", "B1", "productive day"], ["professional", "chuyên nghiệp", "adjective", "B1", "professional manner"],
    ["hire", "thuê; tuyển dụng", "verb", "B1", "hire new staff"], ["resign", "từ chức", "verb", "B2", "resign from a job"],
    ["organize", "tổ chức; sắp xếp", "verb", "A2", "organize a meeting"], ["submit", "nộp", "verb", "B1", "submit a document"],
  ]},
  { category: "Technology", entries: [
    ["computer", "máy tính", "noun", "A1", "use a computer"], ["keyboard", "bàn phím", "noun", "A1", "wireless keyboard"],
    ["screen", "màn hình", "noun", "A1", "touch screen"], ["browser", "trình duyệt", "noun", "A2", "web browser"],
    ["website", "trang web", "noun", "A1", "visit a website"], ["account", "tài khoản", "noun", "A2", "create an account"],
    ["password", "mật khẩu", "noun", "A1", "strong password"], ["file", "tệp", "noun", "A2", "open a file"],
    ["folder", "thư mục", "noun", "A2", "shared folder"], ["download", "tải xuống", "verb", "A2", "download an app"],
    ["upload", "tải lên", "verb", "A2", "upload a photo"], ["network", "mạng", "noun", "B1", "wireless network"],
    ["signal", "tín hiệu", "noun", "B1", "strong signal"], ["software", "phần mềm", "noun", "B1", "install software"],
    ["hardware", "phần cứng", "noun", "B1", "computer hardware"], ["database", "cơ sở dữ liệu", "noun", "B1", "query a database"],
    ["server", "máy chủ", "noun", "B1", "database server"], ["digital", "kỹ thuật số", "adjective", "B1", "digital skills"],
    ["online", "trực tuyến", "adjective", "A1", "online course"], ["secure", "an toàn; bảo mật", "adjective", "B1", "secure connection"],
  ]},
  { category: "Education", entries: [
    ["student", "học sinh; sinh viên", "noun", "A1", "university student"], ["teacher", "giáo viên", "noun", "A1", "English teacher"],
    ["classroom", "lớp học", "noun", "A1", "in the classroom"], ["subject", "môn học; chủ đề", "noun", "A2", "school subject"],
    ["exam", "kỳ thi", "noun", "A1", "pass an exam"], ["grade", "điểm số; cấp lớp", "noun", "A2", "get a good grade"],
    ["textbook", "sách giáo khoa", "noun", "A2", "open a textbook"], ["notebook", "vở ghi", "noun", "A1", "write in a notebook"],
    ["library", "thư viện", "noun", "A1", "public library"], ["research", "nghiên cứu", "noun", "B1", "conduct research"],
    ["theory", "lý thuyết", "noun", "B2", "test a theory"], ["concept", "khái niệm", "noun", "B1", "basic concept"],
    ["calculate", "tính toán", "verb", "B1", "calculate the result"], ["discover", "khám phá", "verb", "A2", "discover a solution"],
    ["explain", "giải thích", "verb", "A2", "explain clearly"], ["compare", "so sánh", "verb", "B1", "compare two ideas"],
    ["summarize", "tóm tắt", "verb", "B1", "summarize a text"], ["discuss", "thảo luận", "verb", "A2", "discuss a topic"],
    ["understand", "hiểu", "verb", "A1", "understand a question"], ["educate", "giáo dục", "verb", "B2", "educate the public"],
  ]},
  { category: "Health", entries: [
    ["doctor", "bác sĩ", "noun", "A1", "see a doctor"], ["nurse", "y tá", "noun", "A1", "qualified nurse"],
    ["patient", "bệnh nhân", "noun", "A2", "treat a patient"], ["clinic", "phòng khám", "noun", "A2", "local clinic"],
    ["hospital", "bệnh viện", "noun", "A1", "go to hospital"], ["medicine", "thuốc", "noun", "A1", "take medicine"],
    ["pain", "cơn đau", "noun", "A2", "feel pain"], ["fever", "sốt", "noun", "A2", "high fever"],
    ["cough", "ho; cơn ho", "noun", "A2", "bad cough"], ["injury", "chấn thương", "noun", "B1", "serious injury"],
    ["energy", "năng lượng", "noun", "A2", "have more energy"], ["sleep", "giấc ngủ; ngủ", "noun", "A1", "get enough sleep"],
    ["rest", "nghỉ ngơi", "noun", "A1", "get some rest"], ["fitness", "thể lực", "noun", "B1", "physical fitness"],
    ["vaccine", "vắc-xin", "noun", "B1", "receive a vaccine"], ["diagnosis", "chẩn đoán", "noun", "B2", "confirm a diagnosis"],
    ["emergency", "tình huống khẩn cấp", "noun", "B1", "medical emergency"], ["mental", "thuộc tinh thần", "adjective", "B1", "mental health"],
    ["physical", "thuộc thể chất", "adjective", "B1", "physical activity"], ["wellness", "sức khỏe toàn diện", "noun", "B2", "wellness program"],
  ]},
  { category: "Nature", entries: [
    ["mountain", "núi", "noun", "A1", "climb a mountain"], ["river", "sông", "noun", "A1", "cross a river"],
    ["ocean", "đại dương", "noun", "A2", "deep ocean"], ["beach", "bãi biển", "noun", "A1", "sandy beach"],
    ["island", "hòn đảo", "noun", "A1", "tropical island"], ["valley", "thung lũng", "noun", "A2", "green valley"],
    ["desert", "sa mạc", "noun", "A2", "dry desert"], ["soil", "đất trồng", "noun", "B1", "rich soil"],
    ["plant", "thực vật; trồng", "noun", "A1", "water a plant"], ["animal", "động vật", "noun", "A1", "wild animal"],
    ["bird", "chim", "noun", "A1", "rare bird"], ["insect", "côn trùng", "noun", "A2", "small insect"],
    ["season", "mùa", "noun", "A1", "rainy season"], ["storm", "bão", "noun", "A2", "powerful storm"],
    ["flood", "lũ lụt", "noun", "B1", "severe flood"], ["temperature", "nhiệt độ", "noun", "A2", "high temperature"],
    ["earth", "trái đất; đất", "noun", "A2", "protect the earth"], ["habitat", "môi trường sống", "noun", "B1", "natural habitat"],
    ["protect", "bảo vệ", "verb", "A2", "protect nature"], ["natural", "tự nhiên", "adjective", "A2", "natural beauty"],
  ]},
  { category: "Society", entries: [
    ["government", "chính phủ", "noun", "B1", "local government"], ["law", "luật", "noun", "B1", "obey the law"],
    ["justice", "công lý", "noun", "B2", "social justice"], ["rights", "các quyền", "noun", "B1", "human rights"],
    ["freedom", "tự do", "noun", "B1", "freedom of speech"], ["election", "cuộc bầu cử", "noun", "B1", "general election"],
    ["vote", "bỏ phiếu; lá phiếu", "verb", "B1", "vote for a candidate"], ["economy", "nền kinh tế", "noun", "B2", "global economy"],
    ["population", "dân số", "noun", "B1", "growing population"], ["employment", "việc làm", "noun", "B2", "employment opportunities"],
    ["poverty", "nghèo đói", "noun", "B2", "reduce poverty"], ["wealth", "sự giàu có", "noun", "B2", "create wealth"],
    ["crime", "tội phạm", "noun", "B1", "prevent crime"], ["safety", "sự an toàn", "noun", "A2", "public safety"],
    ["media", "truyền thông", "noun", "B1", "social media"], ["religion", "tôn giáo", "noun", "B2", "religious freedom"],
    ["identity", "bản sắc; danh tính", "noun", "B2", "cultural identity"], ["diversity", "sự đa dạng", "noun", "B2", "cultural diversity"],
    ["cooperation", "sự hợp tác", "noun", "B2", "international cooperation"], ["development", "sự phát triển", "noun", "B1", "economic development"],
  ]},
  { category: "Communication", entries: [
    ["communicate", "giao tiếp", "verb", "A2", "communicate effectively"], ["express", "bày tỏ", "verb", "B1", "express an opinion"],
    ["whisper", "thì thầm", "verb", "B1", "whisper quietly"], ["shout", "la hét", "verb", "A2", "shout for help"],
    ["announce", "thông báo", "verb", "B1", "announce a decision"], ["persuade", "thuyết phục", "verb", "B2", "persuade someone to"],
    ["complain", "phàn nàn", "verb", "B1", "complain about"], ["promise", "hứa", "verb", "A2", "make a promise"],
    ["warn", "cảnh báo", "verb", "B1", "warn someone about"], ["advise", "khuyên", "verb", "B1", "advise someone to"],
    ["greet", "chào hỏi", "verb", "A2", "greet a visitor"], ["contact", "liên hệ", "verb", "A2", "contact a colleague"],
    ["message", "tin nhắn", "noun", "A1", "send a message"], ["translate", "dịch", "verb", "B1", "translate into English"],
    ["interrupt", "ngắt lời", "verb", "B1", "interrupt politely"], ["respond", "phản hồi", "verb", "B1", "respond to a request"],
    ["debate", "tranh luận", "verb", "B2", "debate an issue"], ["claim", "tuyên bố; cho rằng", "verb", "B2", "claim that"],
    ["admit", "thừa nhận", "verb", "B2", "admit a mistake"], ["deny", "phủ nhận", "verb", "B2", "deny responsibility"],
  ]},
  { category: "Personality & Feelings", entries: [
    ["happy", "vui vẻ", "adjective", "A1", "feel happy"], ["sad", "buồn", "adjective", "A1", "feel sad"],
    ["angry", "tức giận", "adjective", "A1", "angry about"], ["afraid", "sợ hãi", "adjective", "A1", "afraid of"],
    ["surprised", "ngạc nhiên", "adjective", "A2", "surprised by"], ["bored", "buồn chán", "adjective", "A1", "get bored"],
    ["tired", "mệt mỏi", "adjective", "A1", "feel tired"], ["kind", "tử tế", "adjective", "A1", "kind to others"],
    ["honest", "trung thực", "adjective", "A2", "completely honest"], ["polite", "lịch sự", "adjective", "A2", "polite request"],
    ["brave", "dũng cảm", "adjective", "A2", "brave decision"], ["generous", "hào phóng", "adjective", "B1", "generous with time"],
    ["selfish", "ích kỷ", "adjective", "B1", "selfish behavior"], ["serious", "nghiêm túc", "adjective", "A2", "serious problem"],
    ["funny", "hài hước", "adjective", "A1", "funny story"], ["creative", "sáng tạo", "adjective", "A2", "creative idea"],
    ["careful", "cẩn thận", "adjective", "A1", "be careful"], ["nervous", "hồi hộp", "adjective", "A2", "nervous about"],
    ["lonely", "cô đơn", "adjective", "A2", "feel lonely"], ["cheerful", "vui tươi", "adjective", "B1", "cheerful person"],
  ]},
  { category: "Business", entries: [
    ["company", "công ty", "noun", "A2", "international company"], ["market", "thị trường", "noun", "A2", "global market"],
    ["product", "sản phẩm", "noun", "A2", "launch a product"], ["customer", "khách hàng", "noun", "A2", "customer service"],
    ["price", "giá", "noun", "A1", "reasonable price"], ["profit", "lợi nhuận", "noun", "B1", "make a profit"],
    ["loss", "khoản lỗ; mất mát", "noun", "B1", "financial loss"], ["demand", "nhu cầu", "noun", "B2", "meet demand"],
    ["supply", "nguồn cung", "noun", "B2", "supply chain"], ["brand", "thương hiệu", "noun", "B1", "well-known brand"],
    ["sale", "việc bán; đợt giảm giá", "noun", "A2", "on sale"], ["purchase", "mua; sự mua hàng", "noun", "B1", "make a purchase"],
    ["industry", "ngành công nghiệp", "noun", "B1", "technology industry"], ["competition", "sự cạnh tranh", "noun", "B1", "strong competition"],
    ["manufacture", "sản xuất", "verb", "B2", "manufacture goods"], ["distribute", "phân phối", "verb", "B2", "distribute products"],
    ["export", "xuất khẩu", "verb", "B1", "export goods"], ["import", "nhập khẩu", "verb", "B1", "import materials"],
    ["revenue", "doanh thu", "noun", "B2", "increase revenue"], ["consumer", "người tiêu dùng", "noun", "B2", "consumer behavior"],
  ]},
  { category: "Academic English", entries: [
    ["hypothesis", "giả thuyết", "noun", "C1", "test a hypothesis"], ["variable", "biến số", "noun", "B2", "dependent variable"],
    ["data", "dữ liệu", "noun", "B1", "collect data"], ["survey", "khảo sát", "noun", "B1", "conduct a survey"],
    ["sample", "mẫu", "noun", "B2", "representative sample"], ["finding", "phát hiện nghiên cứu", "noun", "B2", "research finding"],
    ["conclusion", "kết luận", "noun", "B1", "reach a conclusion"], ["argument", "lập luận", "noun", "B2", "strong argument"],
    ["citation", "trích dẫn", "noun", "C1", "include a citation"], ["reference", "tài liệu tham khảo", "noun", "B2", "reference list"],
    ["abstract", "bản tóm tắt", "noun", "C1", "research abstract"], ["journal", "tạp chí học thuật", "noun", "B2", "academic journal"],
    ["experiment", "thí nghiệm", "noun", "B1", "conduct an experiment"], ["observe", "quan sát", "verb", "B1", "observe a pattern"],
    ["measure", "đo lường", "verb", "B1", "measure accurately"], ["assess", "đánh giá", "verb", "B2", "assess the impact"],
    ["derive", "suy ra; bắt nguồn", "verb", "C1", "derive from"], ["demonstrate", "chứng minh; thể hiện", "verb", "B2", "demonstrate clearly"],
    ["factor", "yếu tố", "noun", "B1", "key factor"], ["criterion", "tiêu chí", "noun", "C1", "selection criterion"],
  ]},
  { category: "Advanced English", entries: [
    ["ambiguous", "mơ hồ", "adjective", "C1", "ambiguous statement"], ["concise", "ngắn gọn", "adjective", "C1", "concise summary"],
    ["comprehensive", "toàn diện", "adjective", "C1", "comprehensive review"], ["conventional", "thông thường; truyền thống", "adjective", "C1", "conventional approach"],
    ["crucial", "cực kỳ quan trọng", "adjective", "B2", "crucial role"], ["deliberate", "có chủ ý", "adjective", "C1", "deliberate choice"],
    ["diverse", "đa dạng", "adjective", "B2", "diverse community"], ["empirical", "dựa trên thực nghiệm", "adjective", "C1", "empirical evidence"],
    ["explicit", "rõ ràng; tường minh", "adjective", "C1", "explicit instruction"], ["feasible", "khả thi", "adjective", "C1", "feasible solution"],
    ["inherent", "vốn có", "adjective", "C1", "inherent risk"], ["innovative", "đổi mới", "adjective", "B2", "innovative method"],
    ["logical", "hợp lý; logic", "adjective", "B2", "logical conclusion"], ["objective", "khách quan", "adjective", "B2", "objective assessment"],
    ["precise", "chính xác", "adjective", "B2", "precise measurement"], ["prevalent", "phổ biến", "adjective", "C1", "widely prevalent"],
    ["rational", "hợp lý", "adjective", "C1", "rational explanation"], ["subtle", "tinh tế; khó nhận thấy", "adjective", "C1", "subtle difference"],
    ["temporary", "tạm thời", "adjective", "B2", "temporary measure"], ["ultimate", "cuối cùng; tối cao", "adjective", "C1", "ultimate goal"],
  ]},
  { category: "Phrasal Verbs", entries: [
    ["carry on", "tiếp tục", "phrasal verb", "B1", "carry on working"], ["find out", "tìm ra", "phrasal verb", "A2", "find out why"],
    ["give up", "từ bỏ", "phrasal verb", "A2", "give up a habit"], ["look after", "chăm sóc", "phrasal verb", "A2", "look after a child"],
    ["look for", "tìm kiếm", "phrasal verb", "A1", "look for a job"], ["pick up", "nhặt; đón; học được", "phrasal verb", "A2", "pick up a skill"],
    ["put off", "trì hoãn", "phrasal verb", "B1", "put off a meeting"], ["set up", "thiết lập", "phrasal verb", "B1", "set up a business"],
    ["take off", "cất cánh; cởi ra", "phrasal verb", "A2", "plane takes off"], ["turn down", "từ chối; vặn nhỏ", "phrasal verb", "B1", "turn down an offer"],
    ["work out", "tìm ra; tập luyện", "phrasal verb", "B1", "work out a solution"], ["bring up", "đề cập; nuôi dưỡng", "phrasal verb", "B1", "bring up a topic"],
    ["come across", "tình cờ gặp", "phrasal verb", "B1", "come across an article"], ["get along", "hòa hợp", "phrasal verb", "B1", "get along well"],
    ["get over", "vượt qua; hồi phục", "phrasal verb", "B1", "get over an illness"], ["go through", "trải qua; xem kỹ", "phrasal verb", "B1", "go through a change"],
    ["keep up", "theo kịp; duy trì", "phrasal verb", "B1", "keep up the progress"], ["point out", "chỉ ra", "phrasal verb", "B1", "point out a mistake"],
    ["run out", "cạn kiệt", "phrasal verb", "B1", "run out of time"], ["take part", "tham gia", "phrasal verb", "A2", "take part in"],
  ]},
];

const examples = [
  (phrase: string) => [`We practised the phrase “${phrase}” in class today.`, `Hôm nay chúng tôi luyện cụm “${phrase}” trong lớp.`],
  (phrase: string) => [`Can you use “${phrase}” in a complete sentence?`, `Bạn có thể dùng “${phrase}” trong một câu hoàn chỉnh không?`],
  (phrase: string) => [`The dialogue includes the expression “${phrase}”.`, `Đoạn hội thoại có cụm “${phrase}”.`],
  (phrase: string) => [`Remember the common combination “${phrase}”.`, `Hãy ghi nhớ cách kết hợp từ phổ biến “${phrase}”.`],
];

export const coreLexicon = groups.flatMap((group, groupIndex) => group.entries.map((entry, entryIndex) => {
  const [word, meaning, partOfSpeech, level, collocation] = entry;
  const [example, translation] = examples[(groupIndex + entryIndex) % examples.length](collocation);
  return {
    id: `core-${String(groupIndex * 20 + entryIndex + 1).padStart(3, "0")}`,
    word,
    ipa: "",
    meaning,
    partOfSpeech,
    definition: `A useful ${partOfSpeech} for ${group.category.toLowerCase()} contexts.`,
    example,
    translation,
    category: group.category,
    level,
    collocations: [collocation],
  };
}));

