// Additional themed vocabulary for practical and advanced study paths.
type Entry = [word: string, meaning: string, partOfSpeech: string, level: string, collocation: string];

const groups: Array<{ category: string; entries: Entry[] }> = [
  { category: "City & Transport", entries: [
    ["avenue", "đại lộ", "noun", "A2", "tree-lined avenue"], ["pavement", "vỉa hè", "noun", "A2", "walk on the pavement"],
    ["intersection", "giao lộ", "noun", "B1", "busy intersection"], ["pedestrian", "người đi bộ", "noun", "B1", "pedestrian crossing"],
    ["suburb", "vùng ngoại ô", "noun", "B1", "live in the suburbs"], ["downtown", "trung tâm thành phố", "noun", "A2", "downtown area"],
    ["landmark", "địa danh nổi bật", "noun", "B1", "historic landmark"], ["skyscraper", "nhà chọc trời", "noun", "B1", "modern skyscraper"],
    ["resident", "cư dân", "noun", "B1", "local resident"], ["municipality", "chính quyền đô thị", "noun", "C1", "local municipality"],
    ["congestion", "sự ùn tắc", "noun", "B2", "traffic congestion"], ["construction", "việc xây dựng", "noun", "B1", "construction site"],
    ["district", "quận; khu vực", "noun", "B1", "business district"], ["facility", "cơ sở vật chất", "noun", "B1", "public facility"],
    ["housing", "nhà ở", "noun", "B2", "affordable housing"], ["transport", "giao thông vận tải", "noun", "A2", "public transport"],
    ["urban", "thuộc đô thị", "adjective", "B2", "urban planning"], ["accessible", "dễ tiếp cận", "adjective", "B2", "easily accessible"],
    ["infrastructure", "cơ sở hạ tầng", "noun", "C1", "transport infrastructure"], ["architecture", "kiến trúc", "noun", "B2", "modern architecture"],
  ]},
  { category: "Arts & Culture", entries: [
    ["portrait", "tranh chân dung", "noun", "B1", "paint a portrait"], ["landscape", "phong cảnh", "noun", "B1", "rural landscape"],
    ["sculpture", "tác phẩm điêu khắc", "noun", "B1", "stone sculpture"], ["exhibition", "triển lãm", "noun", "B1", "art exhibition"],
    ["gallery", "phòng trưng bày", "noun", "A2", "visit a gallery"], ["performance", "buổi biểu diễn", "noun", "B1", "live performance"],
    ["rhythm", "nhịp điệu", "noun", "B1", "steady rhythm"], ["melody", "giai điệu", "noun", "B1", "simple melody"],
    ["lyrics", "lời bài hát", "noun", "B1", "song lyrics"], ["novel", "tiểu thuyết", "noun", "A2", "historical novel"],
    ["fiction", "văn học hư cấu", "noun", "B1", "science fiction"], ["poetry", "thơ ca", "noun", "B1", "modern poetry"],
    ["author", "tác giả", "noun", "A2", "best-selling author"], ["director", "đạo diễn", "noun", "A2", "film director"],
    ["actor", "diễn viên", "noun", "A1", "lead actor"], ["stage", "sân khấu", "noun", "A2", "on stage"],
    ["scene", "cảnh phim; hiện trường", "noun", "A2", "opening scene"], ["design", "thiết kế", "noun", "A2", "graphic design"],
    ["craft", "đồ thủ công; nghề thủ công", "noun", "B1", "traditional craft"], ["masterpiece", "kiệt tác", "noun", "B2", "literary masterpiece"],
  ]},
  { category: "Sports", entries: [
    ["athlete", "vận động viên", "noun", "B1", "professional athlete"], ["coach", "huấn luyện viên", "noun", "A2", "football coach"],
    ["tournament", "giải đấu", "noun", "B1", "international tournament"], ["championship", "giải vô địch", "noun", "B1", "win a championship"],
    ["score", "ghi điểm; tỷ số", "verb", "A2", "score a goal"], ["goal", "bàn thắng; mục tiêu", "noun", "A1", "achieve a goal"],
    ["training", "sự tập luyện", "noun", "A2", "training session"], ["compete", "thi đấu", "verb", "B1", "compete against"],
    ["defeat", "đánh bại", "verb", "B2", "defeat an opponent"], ["victory", "chiến thắng", "noun", "B1", "claim victory"],
    ["match", "trận đấu", "noun", "A1", "play a match"], ["referee", "trọng tài", "noun", "B1", "match referee"],
    ["stadium", "sân vận động", "noun", "A2", "football stadium"], ["team", "đội", "noun", "A1", "team member"],
    ["opponent", "đối thủ", "noun", "B1", "strong opponent"], ["endurance", "sức bền", "noun", "B2", "build endurance"],
    ["strength", "sức mạnh", "noun", "B1", "physical strength"], ["speed", "tốc độ", "noun", "A2", "at high speed"],
    ["technique", "kỹ thuật", "noun", "B1", "improve technique"], ["spectator", "khán giả", "noun", "B2", "sports spectator"],
  ]},
  { category: "Science", entries: [
    ["organism", "sinh vật", "noun", "B2", "living organism"], ["molecule", "phân tử", "noun", "B2", "water molecule"],
    ["chemical", "hóa chất", "noun", "B1", "chemical reaction"], ["gravity", "trọng lực", "noun", "B1", "force of gravity"],
    ["universe", "vũ trụ", "noun", "B1", "observable universe"], ["planet", "hành tinh", "noun", "A2", "distant planet"],
    ["species", "loài", "noun", "B2", "endangered species"], ["evolution", "sự tiến hóa", "noun", "B2", "theory of evolution"],
    ["gene", "gen", "noun", "B2", "human gene"], ["cell", "tế bào", "noun", "B1", "blood cell"],
    ["laboratory", "phòng thí nghiệm", "noun", "B1", "research laboratory"], ["discovery", "khám phá", "noun", "B1", "scientific discovery"],
    ["matter", "vật chất", "noun", "B2", "state of matter"], ["radiation", "bức xạ", "noun", "B2", "solar radiation"],
    ["element", "nguyên tố; yếu tố", "noun", "B1", "chemical element"], ["compound", "hợp chất", "noun", "B2", "organic compound"],
    ["reaction", "phản ứng", "noun", "B1", "chain reaction"], ["technology", "công nghệ", "noun", "A2", "modern technology"],
    ["scientist", "nhà khoa học", "noun", "A2", "leading scientist"], ["innovation", "sự đổi mới", "noun", "B2", "technological innovation"],
  ]},
  { category: "Law & Justice", entries: [
    ["legal", "hợp pháp; thuộc pháp luật", "adjective", "B1", "legal advice"], ["illegal", "bất hợp pháp", "adjective", "B1", "illegal activity"],
    ["court", "tòa án", "noun", "B1", "appear in court"], ["judge", "thẩm phán", "noun", "B1", "court judge"],
    ["lawyer", "luật sư", "noun", "A2", "defense lawyer"], ["witness", "nhân chứng", "noun", "B1", "key witness"],
    ["trial", "phiên tòa; thử nghiệm", "noun", "B2", "fair trial"], ["sentence", "bản án; câu", "noun", "B1", "prison sentence"],
    ["prison", "nhà tù", "noun", "B1", "go to prison"], ["arrest", "bắt giữ", "verb", "B1", "make an arrest"],
    ["accuse", "buộc tội", "verb", "B2", "accuse someone of"], ["innocent", "vô tội", "adjective", "B1", "prove innocent"],
    ["guilty", "có tội", "adjective", "B1", "find guilty"], ["offense", "hành vi phạm tội", "noun", "B2", "criminal offense"],
    ["penalty", "hình phạt", "noun", "B1", "pay a penalty"], ["fine", "tiền phạt", "noun", "B1", "receive a fine"],
    ["appeal", "kháng cáo", "verb", "B2", "appeal a decision"], ["authority", "cơ quan chức năng; thẩm quyền", "noun", "B2", "local authority"],
    ["constitution", "hiến pháp", "noun", "C1", "written constitution"], ["regulation", "quy định", "noun", "B2", "safety regulation"],
  ]},
  { category: "Shopping", entries: [
    ["bargain", "món hời", "noun", "B1", "find a bargain"], ["refund", "tiền hoàn lại", "noun", "B1", "request a refund"],
    ["warranty", "bảo hành", "noun", "B1", "one-year warranty"], ["label", "nhãn", "noun", "A2", "read the label"],
    ["cash", "tiền mặt", "noun", "A1", "pay in cash"], ["credit", "tín dụng", "noun", "B1", "credit card"],
    ["checkout", "quầy thanh toán", "noun", "A2", "at the checkout"], ["basket", "giỏ", "noun", "A1", "shopping basket"],
    ["trolley", "xe đẩy", "noun", "A2", "shopping trolley"], ["shopkeeper", "chủ cửa hàng", "noun", "B1", "local shopkeeper"],
    ["stock", "hàng tồn kho", "noun", "B1", "in stock"], ["cost", "chi phí; có giá", "noun", "A2", "total cost"],
    ["charge", "tính phí; khoản phí", "verb", "B1", "charge a fee"], ["fee", "lệ phí", "noun", "B1", "service fee"],
    ["delivery", "việc giao hàng", "noun", "A2", "free delivery"], ["quality", "chất lượng", "noun", "B1", "high quality"],
    ["quantity", "số lượng", "noun", "B2", "large quantity"], ["expensive", "đắt", "adjective", "A1", "too expensive"],
    ["cheap", "rẻ", "adjective", "A1", "cheap option"], ["select", "lựa chọn", "verb", "B1", "select an item"],
  ]},
  { category: "Relationships", entries: [
    ["acquaintance", "người quen", "noun", "B2", "casual acquaintance"], ["friendship", "tình bạn", "noun", "A2", "close friendship"],
    ["partner", "bạn đời; đối tác", "noun", "A2", "life partner"], ["spouse", "vợ hoặc chồng", "noun", "B2", "support a spouse"],
    ["sibling", "anh chị em ruột", "noun", "B1", "older sibling"], ["loyalty", "lòng trung thành", "noun", "B2", "show loyalty"],
    ["empathy", "sự đồng cảm", "noun", "B2", "show empathy"], ["affection", "tình cảm", "noun", "B2", "deep affection"],
    ["bond", "mối gắn kết", "noun", "B1", "strong bond"], ["cooperate", "hợp tác", "verb", "B1", "cooperate with"],
    ["misunderstand", "hiểu lầm", "verb", "B1", "easily misunderstand"], ["reconcile", "làm hòa", "verb", "C1", "reconcile with"],
    ["admire", "ngưỡng mộ", "verb", "B1", "greatly admire"], ["appreciate", "trân trọng", "verb", "B1", "appreciate the help"],
    ["criticize", "chỉ trích", "verb", "B2", "criticize unfairly"], ["forgive", "tha thứ", "verb", "B1", "forgive a mistake"],
    ["depend", "phụ thuộc", "verb", "B1", "depend on"], ["share", "chia sẻ", "verb", "A2", "share an experience"],
    ["connect", "kết nối", "verb", "A2", "connect with people"], ["distant", "xa cách; xa xôi", "adjective", "B1", "distant relative"],
  ]},
  { category: "Language Learning", entries: [
    ["fluency", "độ trôi chảy", "noun", "B2", "improve fluency"], ["accuracy", "độ chính xác", "noun", "B2", "grammar accuracy"],
    ["pronunciation", "phát âm", "noun", "B1", "clear pronunciation"], ["accent", "giọng", "noun", "B1", "regional accent"],
    ["grammar", "ngữ pháp", "noun", "A2", "grammar rule"], ["phrase", "cụm từ", "noun", "A2", "useful phrase"],
    ["idiom", "thành ngữ", "noun", "B1", "common idiom"], ["clause", "mệnh đề", "noun", "B2", "relative clause"],
    ["context", "ngữ cảnh", "noun", "B1", "in context"], ["speaker", "người nói", "noun", "A2", "native speaker"],
    ["listener", "người nghe", "noun", "A2", "active listener"], ["bilingual", "song ngữ", "adjective", "B2", "bilingual dictionary"],
    ["mistake", "lỗi sai", "noun", "A1", "make a mistake"], ["correction", "sự sửa lỗi", "noun", "B1", "self-correction"],
    ["repetition", "sự lặp lại", "noun", "B1", "spaced repetition"], ["comprehension", "khả năng hiểu", "noun", "B2", "reading comprehension"],
    ["paraphrase", "diễn đạt lại", "verb", "B2", "paraphrase an idea"], ["infer", "suy luận", "verb", "B2", "infer meaning"],
    ["scan", "đọc quét để tìm thông tin", "verb", "B1", "scan for details"], ["skim", "đọc lướt", "verb", "B1", "skim a text"],
  ]},
  { category: "Advanced Verbs", entries: [
    ["acknowledge", "thừa nhận", "verb", "C1", "acknowledge a limitation"], ["anticipate", "dự đoán trước", "verb", "C1", "anticipate a problem"],
    ["articulate", "diễn đạt rõ", "verb", "C1", "articulate an argument"], ["attain", "đạt được", "verb", "C1", "attain a goal"],
    ["compensate", "bù đắp", "verb", "C1", "compensate for"], ["contradict", "mâu thuẫn; phủ định", "verb", "C1", "contradict a claim"],
    ["convey", "truyền đạt", "verb", "C1", "convey a message"], ["distinguish", "phân biệt", "verb", "B2", "distinguish between"],
    ["enhance", "nâng cao", "verb", "B2", "enhance performance"], ["facilitate", "tạo điều kiện", "verb", "C1", "facilitate learning"],
    ["illustrate", "minh họa", "verb", "B2", "illustrate a point"], ["imply", "ngụ ý", "verb", "B2", "imply that"],
    ["justify", "biện minh; chứng minh hợp lý", "verb", "B2", "justify a decision"], ["maintain", "duy trì; cho rằng", "verb", "B2", "maintain a standard"],
    ["perceive", "nhận thức", "verb", "C1", "perceive a difference"], ["pursue", "theo đuổi", "verb", "C1", "pursue a career"],
    ["reinforce", "củng cố", "verb", "C1", "reinforce an idea"], ["retain", "giữ lại; ghi nhớ", "verb", "C1", "retain information"],
    ["specify", "nêu rõ", "verb", "B2", "specify a requirement"], ["undergo", "trải qua", "verb", "C1", "undergo a change"],
  ]},
  { category: "Advanced Concepts", entries: [
    ["allocation", "sự phân bổ", "noun", "C1", "resource allocation"], ["capacity", "năng lực; sức chứa", "noun", "B2", "production capacity"],
    ["circumstance", "hoàn cảnh", "noun", "B2", "under the circumstances"], ["consequence", "hậu quả", "noun", "B2", "serious consequence"],
    ["constraint", "sự hạn chế", "noun", "C1", "time constraint"], ["controversy", "tranh cãi", "noun", "C1", "cause controversy"],
    ["credibility", "độ tin cậy", "noun", "C1", "gain credibility"], ["dimension", "khía cạnh; chiều", "noun", "C1", "social dimension"],
    ["incentive", "động lực khuyến khích", "noun", "C1", "financial incentive"], ["mechanism", "cơ chế", "noun", "C1", "control mechanism"],
    ["notion", "quan niệm", "noun", "C1", "challenge a notion"], ["phenomenon", "hiện tượng", "noun", "C1", "global phenomenon"],
    ["proportion", "tỷ lệ", "noun", "B2", "large proportion"], ["scope", "phạm vi", "noun", "C1", "beyond the scope"],
    ["tendency", "xu hướng", "noun", "C1", "general tendency"], ["transition", "sự chuyển đổi", "noun", "B2", "smooth transition"],
    ["validity", "tính hợp lệ", "noun", "C1", "question the validity"], ["welfare", "phúc lợi", "noun", "C1", "public welfare"],
    ["benchmark", "mốc chuẩn", "noun", "C1", "industry benchmark"], ["discrepancy", "sự khác biệt bất thường", "noun", "C1", "explain a discrepancy"],
  ]},
];

const sentencePatterns = [
  (phrase: string) => [`The lesson shows how to use “${phrase}” naturally.`, `Bài học chỉ cách dùng “${phrase}” tự nhiên.`],
  (phrase: string) => [`Write one sentence with the phrase “${phrase}”.`, `Hãy viết một câu với cụm “${phrase}”.`],
  (phrase: string) => [`You may hear “${phrase}” in real conversations.`, `Bạn có thể nghe cụm “${phrase}” trong hội thoại thực tế.`],
  (phrase: string) => [`Today we will remember the combination “${phrase}”.`, `Hôm nay chúng ta sẽ ghi nhớ cách kết hợp “${phrase}”.`],
];

export const topicVocabulary = groups.flatMap((group, groupIndex) => group.entries.map((entry, entryIndex) => {
  const [word, meaning, partOfSpeech, level, collocation] = entry;
  const [example, translation] = sentencePatterns[(groupIndex + entryIndex) % sentencePatterns.length](collocation);
  return {
    id: `topic-${String(groupIndex * 20 + entryIndex + 1).padStart(3, "0")}`,
    word,
    ipa: "",
    meaning,
    definition: `A useful ${partOfSpeech} used in ${group.category.toLowerCase()} contexts.`,
    partOfSpeech,
    example,
    translation,
    category: group.category,
    level,
    collocations: [collocation],
  };
}));

