// A second vocabulary pack for broader everyday and professional coverage.
type WordTuple = [
  word: string,
  ipa: string,
  meaning: string,
  partOfSpeech: string,
  definition: string,
  example: string,
  translation: string,
  category: string,
  level: string,
  collocation: string,
];

const words: WordTuple[] = [
  // Family & relationships
  ["parent", "/ˈperənt/", "cha hoặc mẹ", "noun", "A mother or father.", "My parents always listen to my ideas.", "Cha mẹ tôi luôn lắng nghe ý tưởng của tôi.", "Family", "A1", "single parent"],
  ["relative", "/ˈrelətɪv/", "họ hàng", "noun", "A person who belongs to the same family.", "We visit our relatives during the holiday.", "Chúng tôi thăm họ hàng vào dịp nghỉ lễ.", "Family", "A2", "close relative"],
  ["couple", "/ˈkʌpəl/", "cặp đôi", "noun", "Two people who are married or in a romantic relationship.", "The couple moved into a new apartment.", "Cặp đôi đã chuyển đến một căn hộ mới.", "Family", "A2", "young couple"],
  ["childhood", "/ˈtʃaɪldhʊd/", "thời thơ ấu", "noun", "The period of life when a person is a child.", "This song reminds me of my childhood.", "Bài hát này gợi tôi nhớ về thời thơ ấu.", "Family", "B1", "childhood memory"],
  ["support", "/səˈpɔːrt/", "ủng hộ; hỗ trợ", "verb", "To help or encourage someone.", "Her family supported her decision to study abroad.", "Gia đình đã ủng hộ quyết định du học của cô ấy.", "Relationships", "A2", "support a decision"],
  ["trust", "/trʌst/", "tin tưởng", "verb", "To believe that someone is honest and dependable.", "Good friends trust each other.", "Những người bạn tốt tin tưởng lẫn nhau.", "Relationships", "A2", "build trust"],
  ["respect", "/rɪˈspekt/", "tôn trọng", "verb", "To admire someone and treat them with care.", "We should respect different opinions.", "Chúng ta nên tôn trọng những ý kiến khác nhau.", "Relationships", "A2", "show respect"],
  ["argue", "/ˈɑːrɡjuː/", "tranh cãi", "verb", "To speak angrily because you disagree.", "They sometimes argue about household chores.", "Đôi khi họ tranh cãi về việc nhà.", "Relationships", "B1", "argue about"],
  ["apologize", "/əˈpɑːlədʒaɪz/", "xin lỗi", "verb", "To say that you are sorry for something you did.", "He apologized for arriving late.", "Anh ấy xin lỗi vì đến muộn.", "Relationships", "A2", "apologize for"],
  ["encourage", "/ɪnˈkɜːrɪdʒ/", "khuyến khích", "verb", "To give someone confidence or hope.", "My teacher encouraged me to speak more often.", "Giáo viên khuyến khích tôi nói thường xuyên hơn.", "Relationships", "B1", "encourage someone to"],

  // Home
  ["household", "/ˈhaʊshoʊld/", "hộ gia đình", "noun", "All the people who live together in one home.", "The average household uses less water now.", "Mỗi hộ gia đình trung bình hiện sử dụng ít nước hơn.", "Home", "B1", "household income"],
  ["furniture", "/ˈfɜːrnɪtʃər/", "đồ nội thất", "noun", "Large objects such as tables, beds, and chairs in a room.", "We bought simple furniture for the living room.", "Chúng tôi mua đồ nội thất đơn giản cho phòng khách.", "Home", "A2", "a piece of furniture"],
  ["appliance", "/əˈplaɪəns/", "thiết bị gia dụng", "noun", "A machine used in the home, such as a fridge or washing machine.", "This appliance uses very little electricity.", "Thiết bị này sử dụng rất ít điện.", "Home", "B1", "kitchen appliance"],
  ["balcony", "/ˈbælkəni/", "ban công", "noun", "A platform outside an upper floor of a building.", "She grows herbs on the balcony.", "Cô ấy trồng rau thơm trên ban công.", "Home", "A2", "private balcony"],
  ["rent", "/rent/", "thuê", "verb", "To pay to use a home or object for a period of time.", "They rent a small house near the university.", "Họ thuê một căn nhà nhỏ gần trường đại học.", "Home", "A2", "rent an apartment"],
  ["repair", "/rɪˈper/", "sửa chữa", "verb", "To fix something that is damaged or broken.", "A technician repaired our washing machine.", "Một kỹ thuật viên đã sửa máy giặt của chúng tôi.", "Home", "A2", "repair damage"],
  ["tidy", "/ˈtaɪdi/", "gọn gàng", "adjective", "Arranged neatly and with everything in its place.", "Please keep your room tidy.", "Vui lòng giữ phòng của bạn gọn gàng.", "Home", "A1", "keep tidy"],
  ["comfortable", "/ˈkʌmftəbəl/", "thoải mái", "adjective", "Making you feel physically relaxed.", "This chair is comfortable enough for reading.", "Chiếc ghế này đủ thoải mái để đọc sách.", "Home", "A2", "feel comfortable"],
  ["neighborhood", "/ˈneɪbərhʊd/", "khu phố", "noun", "The area around where someone lives.", "There is a quiet park in our neighborhood.", "Có một công viên yên tĩnh trong khu phố của chúng tôi.", "Home", "A2", "safe neighborhood"],
  ["utility", "/juːˈtɪləti/", "dịch vụ tiện ích", "noun", "A service such as electricity, water, or gas.", "The monthly rent does not include utilities.", "Tiền thuê hằng tháng không bao gồm các dịch vụ tiện ích.", "Home", "B1", "utility bill"],

  // Education
  ["assignment", "/əˈsaɪnmənt/", "bài tập được giao", "noun", "A piece of work given to a student.", "The history assignment is due on Monday.", "Bài tập lịch sử đến hạn vào thứ Hai.", "Education", "A2", "complete an assignment"],
  ["lecture", "/ˈlektʃər/", "bài giảng", "noun", "A formal talk given to a group of students.", "The lecture introduced a new research method.", "Bài giảng giới thiệu một phương pháp nghiên cứu mới.", "Education", "B1", "attend a lecture"],
  ["revise", "/rɪˈvaɪz/", "ôn tập", "verb", "To study material again before an examination.", "I revise new vocabulary every evening.", "Tôi ôn từ vựng mới mỗi tối.", "Education", "A2", "revise for an exam"],
  ["memorize", "/ˈmeməraɪz/", "ghi nhớ", "verb", "To learn something so that you can remember it exactly.", "Try to memorize phrases instead of single words.", "Hãy thử ghi nhớ các cụm từ thay vì từ riêng lẻ.", "Education", "B1", "memorize a phrase"],
  ["concentrate", "/ˈkɑːnsəntreɪt/", "tập trung", "verb", "To direct all your attention toward one activity.", "I concentrate better in a quiet room.", "Tôi tập trung tốt hơn trong một căn phòng yên tĩnh.", "Education", "B1", "concentrate on"],
  ["curious", "/ˈkjʊriəs/", "tò mò; ham tìm hiểu", "adjective", "Wanting to learn or know more about something.", "Curious learners ask useful questions.", "Những người học ham tìm hiểu đặt ra các câu hỏi hữu ích.", "Education", "A2", "curious about"],
  ["knowledge", "/ˈnɑːlɪdʒ/", "kiến thức", "noun", "Information and understanding gained through learning.", "Reading widely increases your knowledge.", "Đọc nhiều giúp tăng kiến thức của bạn.", "Education", "B1", "gain knowledge"],
  ["skill", "/skɪl/", "kỹ năng", "noun", "An ability developed through training and experience.", "Listening is an important communication skill.", "Lắng nghe là một kỹ năng giao tiếp quan trọng.", "Education", "A2", "develop a skill"],
  ["progress", "/ˈprɑːɡres/", "sự tiến bộ", "noun", "Improvement toward a goal.", "You have made excellent progress this month.", "Bạn đã tiến bộ rất tốt trong tháng này.", "Education", "A2", "make progress"],
  ["graduate", "/ˈɡrædʒueɪt/", "tốt nghiệp", "verb", "To successfully complete a course at a school or university.", "She graduated from university last year.", "Cô ấy tốt nghiệp đại học năm ngoái.", "Education", "B1", "graduate from"],

  // Health
  ["symptom", "/ˈsɪmptəm/", "triệu chứng", "noun", "A physical sign that may indicate an illness.", "A sore throat was his first symptom.", "Đau họng là triệu chứng đầu tiên của anh ấy.", "Health", "B1", "common symptom"],
  ["treatment", "/ˈtriːtmənt/", "sự điều trị", "noun", "Medical care given for an illness or injury.", "The treatment helped her recover quickly.", "Việc điều trị giúp cô ấy hồi phục nhanh chóng.", "Health", "B1", "receive treatment"],
  ["recover", "/rɪˈkʌvər/", "hồi phục", "verb", "To become healthy again after an illness or injury.", "He needs time to recover after the operation.", "Anh ấy cần thời gian hồi phục sau ca phẫu thuật.", "Health", "A2", "recover from"],
  ["prevent", "/prɪˈvent/", "ngăn ngừa", "verb", "To stop something from happening.", "Regular exercise can help prevent illness.", "Tập thể dục thường xuyên có thể giúp ngăn ngừa bệnh tật.", "Health", "B1", "prevent disease"],
  ["balanced", "/ˈbælənst/", "cân bằng", "adjective", "Containing the right amounts of different things.", "A balanced diet includes several food groups.", "Một chế độ ăn cân bằng gồm nhiều nhóm thực phẩm.", "Health", "B1", "balanced diet"],
  ["nutrition", "/nuˈtrɪʃən/", "dinh dưỡng", "noun", "The process of getting the food needed for health and growth.", "Good nutrition supports learning and concentration.", "Dinh dưỡng tốt hỗ trợ việc học và tập trung.", "Health", "B1", "good nutrition"],
  ["exercise", "/ˈeksərsaɪz/", "tập thể dục", "noun", "Physical activity done to stay healthy or become stronger.", "Walking is a simple form of exercise.", "Đi bộ là một hình thức tập thể dục đơn giản.", "Health", "A1", "regular exercise"],
  ["breathe", "/briːð/", "thở", "verb", "To take air into and send it out of the lungs.", "Breathe slowly before you begin speaking.", "Hãy thở chậm trước khi bắt đầu nói.", "Health", "A2", "breathe deeply"],
  ["headache", "/ˈhedeɪk/", "đau đầu", "noun", "A pain in your head.", "I took a short break because I had a headache.", "Tôi nghỉ một lúc vì bị đau đầu.", "Health", "A1", "have a headache"],
  ["healthy", "/ˈhelθi/", "khỏe mạnh", "adjective", "Physically well and not ill.", "A healthy routine includes enough sleep.", "Một thói quen lành mạnh bao gồm ngủ đủ giấc.", "Health", "A1", "stay healthy"],

  // Finance
  ["budget", "/ˈbʌdʒɪt/", "ngân sách", "noun", "A plan showing how much money can be spent.", "We created a budget for our holiday.", "Chúng tôi lập ngân sách cho kỳ nghỉ.", "Finance", "B1", "set a budget"],
  ["afford", "/əˈfɔːrd/", "có đủ khả năng chi trả", "verb", "To have enough money to pay for something.", "I cannot afford a new laptop this month.", "Tháng này tôi không đủ khả năng mua laptop mới.", "Finance", "B1", "can afford"],
  ["expense", "/ɪkˈspens/", "chi phí", "noun", "Money spent in order to buy or do something.", "Transport is our largest monthly expense.", "Đi lại là chi phí hằng tháng lớn nhất của chúng tôi.", "Finance", "B1", "business expense"],
  ["income", "/ˈɪnkʌm/", "thu nhập", "noun", "Money received regularly from work or investments.", "Her income increased after the promotion.", "Thu nhập của cô ấy tăng sau khi thăng chức.", "Finance", "B1", "monthly income"],
  ["savings", "/ˈseɪvɪŋz/", "tiền tiết kiệm", "noun", "Money kept for future use instead of being spent.", "They used their savings to start a business.", "Họ dùng tiền tiết kiệm để khởi nghiệp.", "Finance", "B1", "personal savings"],
  ["debt", "/det/", "nợ", "noun", "Money that is owed to another person or organization.", "He has a plan to pay off his debt.", "Anh ấy có kế hoạch trả hết nợ.", "Finance", "B2", "pay off debt"],
  ["invest", "/ɪnˈvest/", "đầu tư", "verb", "To use money, time, or effort in hopes of a future benefit.", "The company will invest in staff training.", "Công ty sẽ đầu tư vào đào tạo nhân viên.", "Finance", "B1", "invest in"],
  ["payment", "/ˈpeɪmənt/", "khoản thanh toán", "noun", "An amount of money paid for something.", "Your payment was received successfully.", "Khoản thanh toán của bạn đã được nhận thành công.", "Finance", "A2", "make a payment"],
  ["salary", "/ˈsæləri/", "lương", "noun", "A fixed amount of money paid regularly for work.", "The position offers a competitive salary.", "Vị trí này cung cấp mức lương cạnh tranh.", "Finance", "B1", "annual salary"],
  ["value", "/ˈvæljuː/", "giá trị", "noun", "The usefulness or importance of something compared with its cost.", "This course offers good value for beginners.", "Khóa học này mang lại giá trị tốt cho người mới bắt đầu.", "Finance", "B1", "good value"],

  // Emotions
  ["anxious", "/ˈæŋkʃəs/", "lo lắng", "adjective", "Worried or nervous about something uncertain.", "She felt anxious before the interview.", "Cô ấy cảm thấy lo lắng trước buổi phỏng vấn.", "Emotions", "B1", "feel anxious"],
  ["grateful", "/ˈɡreɪtfəl/", "biết ơn", "adjective", "Feeling thankful for help or kindness.", "I am grateful for your honest advice.", "Tôi biết ơn lời khuyên chân thành của bạn.", "Emotions", "B1", "grateful for"],
  ["disappointed", "/ˌdɪsəˈpɔɪntɪd/", "thất vọng", "adjective", "Unhappy because something was not as good as expected.", "We were disappointed with the final result.", "Chúng tôi thất vọng với kết quả cuối cùng.", "Emotions", "A2", "disappointed with"],
  ["excited", "/ɪkˈsaɪtɪd/", "hào hứng", "adjective", "Very happy and enthusiastic about something.", "The students are excited about the new course.", "Các học viên hào hứng với khóa học mới.", "Emotions", "A1", "excited about"],
  ["calm", "/kɑːm/", "bình tĩnh", "adjective", "Relaxed and not worried or angry.", "Try to remain calm during the presentation.", "Hãy cố giữ bình tĩnh trong khi thuyết trình.", "Emotions", "A2", "remain calm"],
  ["proud", "/praʊd/", "tự hào", "adjective", "Pleased about something you or another person has achieved.", "Her parents are proud of her progress.", "Cha mẹ cô ấy tự hào về sự tiến bộ của cô.", "Emotions", "A2", "proud of"],
  ["embarrassed", "/ɪmˈbærəst/", "xấu hổ", "adjective", "Feeling uncomfortable because of a mistake or awkward situation.", "I felt embarrassed when I forgot his name.", "Tôi cảm thấy xấu hổ khi quên tên anh ấy.", "Emotions", "B1", "feel embarrassed"],
  ["frustrated", "/ˈfrʌstreɪtɪd/", "bực bội", "adjective", "Annoyed because you cannot achieve what you want.", "He became frustrated with the slow connection.", "Anh ấy bực bội vì kết nối chậm.", "Emotions", "B1", "frustrated with"],
  ["relieved", "/rɪˈliːvd/", "nhẹ nhõm", "adjective", "Happy because a worry or difficult situation has ended.", "I was relieved to hear that everyone was safe.", "Tôi nhẹ nhõm khi biết mọi người đều an toàn.", "Emotions", "B1", "feel relieved"],
  ["motivated", "/ˈmoʊtəveɪtɪd/", "có động lực", "adjective", "Eager and willing to work toward a goal.", "Small wins keep learners motivated.", "Những thành công nhỏ giúp người học duy trì động lực.", "Emotions", "B1", "highly motivated"],

  // Media
  ["headline", "/ˈhedlaɪn/", "tiêu đề tin", "noun", "The title of a newspaper or online news story.", "The headline did not accurately describe the article.", "Tiêu đề không mô tả chính xác bài báo.", "Media", "B1", "news headline"],
  ["article", "/ˈɑːrtɪkəl/", "bài báo", "noun", "A piece of writing published in a newspaper, magazine, or website.", "I read an article about language learning.", "Tôi đọc một bài báo về việc học ngôn ngữ.", "Media", "A2", "read an article"],
  ["broadcast", "/ˈbrɔːdkæst/", "phát sóng", "verb", "To send a program by television, radio, or the internet.", "The interview will be broadcast live tonight.", "Buổi phỏng vấn sẽ được phát sóng trực tiếp tối nay.", "Media", "B2", "broadcast live"],
  ["source", "/sɔːrs/", "nguồn thông tin", "noun", "A person, document, or place that provides information.", "Always check the source before sharing a story.", "Luôn kiểm tra nguồn trước khi chia sẻ một câu chuyện.", "Media", "B1", "reliable source"],
  ["audience", "/ˈɔːdiəns/", "khán giả", "noun", "The people who watch, read, or listen to something.", "The podcast has a young international audience.", "Podcast có lượng khán giả quốc tế trẻ.", "Media", "B1", "target audience"],
  ["publish", "/ˈpʌblɪʃ/", "xuất bản", "verb", "To make writing or other content available to the public.", "The magazine publishes a new issue every month.", "Tạp chí xuất bản một số mới mỗi tháng.", "Media", "B1", "publish online"],
  ["journalist", "/ˈdʒɜːrnəlɪst/", "nhà báo", "noun", "A person who reports news for newspapers, television, or other media.", "The journalist interviewed local residents.", "Nhà báo đã phỏng vấn cư dân địa phương.", "Media", "A2", "investigative journalist"],
  ["interview", "/ˈɪntərvjuː/", "cuộc phỏng vấn", "noun", "A conversation in which one person asks another questions.", "The interview focused on her new project.", "Cuộc phỏng vấn tập trung vào dự án mới của cô ấy.", "Media", "A2", "conduct an interview"],
  ["advertisement", "/ˌædvərˈtaɪzmənt/", "quảng cáo", "noun", "A message designed to persuade people to buy or use something.", "The advertisement makes an unrealistic promise.", "Quảng cáo đưa ra một lời hứa không thực tế.", "Media", "B1", "online advertisement"],
  ["subscribe", "/səbˈskraɪb/", "đăng ký theo dõi", "verb", "To arrange to receive content or a service regularly.", "You can subscribe to the weekly newsletter.", "Bạn có thể đăng ký nhận bản tin hằng tuần.", "Media", "B1", "subscribe to"],

  // Society
  ["community", "/kəˈmjuːnəti/", "cộng đồng", "noun", "People living in one area or sharing common interests.", "The library serves the whole community.", "Thư viện phục vụ toàn bộ cộng đồng.", "Society", "A2", "local community"],
  ["culture", "/ˈkʌltʃər/", "văn hóa", "noun", "The customs, arts, and ideas of a particular society.", "Food is an important part of local culture.", "Ẩm thực là một phần quan trọng của văn hóa địa phương.", "Society", "A2", "cultural awareness"],
  ["tradition", "/trəˈdɪʃən/", "truyền thống", "noun", "A belief or way of doing something passed through generations.", "The festival celebrates an ancient tradition.", "Lễ hội tôn vinh một truyền thống lâu đời.", "Society", "B1", "follow a tradition"],
  ["volunteer", "/ˌvɑːlənˈtɪr/", "tình nguyện viên", "noun", "A person who offers to work without being paid.", "Volunteers planted trees beside the school.", "Các tình nguyện viên trồng cây bên cạnh trường học.", "Society", "A2", "community volunteer"],
  ["equality", "/ɪˈkwɑːləti/", "sự bình đẳng", "noun", "The state of having the same rights and opportunities.", "The policy aims to improve equality in education.", "Chính sách nhằm cải thiện sự bình đẳng trong giáo dục.", "Society", "B2", "equal opportunity"],
  ["access", "/ˈækses/", "quyền tiếp cận", "noun", "The opportunity or right to use or obtain something.", "Every child should have access to education.", "Mọi trẻ em nên được tiếp cận giáo dục.", "Society", "B1", "access to"],
  ["policy", "/ˈpɑːləsi/", "chính sách", "noun", "An official plan or set of rules used by an organization or government.", "The company introduced a flexible work policy.", "Công ty đưa ra chính sách làm việc linh hoạt.", "Society", "B2", "public policy"],
  ["citizen", "/ˈsɪtɪzən/", "công dân", "noun", "A legally recognized member of a country.", "Citizens were invited to discuss the proposal.", "Người dân được mời thảo luận về đề xuất.", "Society", "B1", "local citizen"],
  ["public", "/ˈpʌblɪk/", "công cộng", "adjective", "Connected with or available to all people.", "The city improved its public transport system.", "Thành phố cải thiện hệ thống giao thông công cộng.", "Society", "A2", "public service"],
  ["responsibility", "/rɪˌspɑːnsəˈbɪləti/", "trách nhiệm", "noun", "A duty to deal with or take care of something.", "Protecting customer data is our responsibility.", "Bảo vệ dữ liệu khách hàng là trách nhiệm của chúng tôi.", "Society", "B1", "take responsibility"],

  // Nature
  ["climate", "/ˈklaɪmət/", "khí hậu", "noun", "The usual weather conditions of a region over a long period.", "The island has a warm and humid climate.", "Hòn đảo có khí hậu ấm và ẩm.", "Environment", "B1", "tropical climate"],
  ["pollution", "/pəˈluːʃən/", "ô nhiễm", "noun", "Damage caused by harmful substances entering the environment.", "The city is working to reduce air pollution.", "Thành phố đang nỗ lực giảm ô nhiễm không khí.", "Environment", "B1", "air pollution"],
  ["recycle", "/ˌriːˈsaɪkəl/", "tái chế", "verb", "To process used materials so they can be used again.", "We recycle paper, glass, and metal at work.", "Chúng tôi tái chế giấy, thủy tinh và kim loại tại nơi làm việc.", "Environment", "A2", "recycle waste"],
  ["renewable", "/rɪˈnuːəbəl/", "có thể tái tạo", "adjective", "Able to be naturally replaced and used again.", "Solar power is a renewable source of energy.", "Năng lượng mặt trời là một nguồn năng lượng tái tạo.", "Environment", "B2", "renewable energy"],
  ["wildlife", "/ˈwaɪldlaɪf/", "động vật hoang dã", "noun", "Animals and plants living naturally in an area.", "The wetland provides a home for wildlife.", "Vùng đất ngập nước là nơi sinh sống của động vật hoang dã.", "Environment", "B1", "protect wildlife"],
  ["forest", "/ˈfɔːrɪst/", "rừng", "noun", "A large area covered mainly with trees.", "The forest stores carbon and protects the soil.", "Rừng lưu trữ carbon và bảo vệ đất.", "Environment", "A2", "rain forest"],
  ["drought", "/draʊt/", "hạn hán", "noun", "A long period with little or no rain.", "The drought damaged crops across the region.", "Hạn hán làm hư hại mùa màng trên toàn khu vực.", "Environment", "B2", "severe drought"],
  ["resource", "/ˈriːsɔːrs/", "tài nguyên", "noun", "A useful supply of material, money, or ability.", "Fresh water is a limited natural resource.", "Nước ngọt là một tài nguyên thiên nhiên có hạn.", "Environment", "B1", "natural resource"],
  ["conserve", "/kənˈsɜːrv/", "bảo tồn; tiết kiệm", "verb", "To protect something and avoid wasting it.", "The new system helps conserve water.", "Hệ thống mới giúp tiết kiệm nước.", "Environment", "B2", "conserve energy"],
  ["ecosystem", "/ˈiːkoʊsɪstəm/", "hệ sinh thái", "noun", "A community of living things and their natural environment.", "Plastic waste can damage the marine ecosystem.", "Rác thải nhựa có thể làm hại hệ sinh thái biển.", "Environment", "B2", "marine ecosystem"],

  // Leadership
  ["leadership", "/ˈliːdərʃɪp/", "khả năng lãnh đạo", "noun", "The ability to guide and influence a group.", "Strong leadership helped the team through the change.", "Khả năng lãnh đạo tốt giúp nhóm vượt qua thay đổi.", "Leadership", "B2", "leadership skills"],
  ["strategy", "/ˈstrætədʒi/", "chiến lược", "noun", "A detailed plan for achieving a goal.", "Our strategy focuses on long-term customer trust.", "Chiến lược của chúng tôi tập trung vào niềm tin lâu dài của khách hàng.", "Leadership", "B2", "develop a strategy"],
  ["decision", "/dɪˈsɪʒən/", "quyết định", "noun", "A choice made after considering different possibilities.", "We need to make a decision by Friday.", "Chúng ta cần đưa ra quyết định trước thứ Sáu.", "Leadership", "A2", "make a decision"],
  ["delegate", "/ˈdeləɡeɪt/", "giao việc", "verb", "To give responsibility for a task to another person.", "Good managers delegate tasks clearly.", "Những quản lý giỏi giao việc một cách rõ ràng.", "Leadership", "B2", "delegate responsibility"],
  ["motivate", "/ˈmoʊtəveɪt/", "tạo động lực", "verb", "To make someone willing and eager to act.", "Clear goals motivate the team to improve.", "Mục tiêu rõ ràng tạo động lực để nhóm cải thiện.", "Leadership", "B1", "motivate a team"],
  ["collaborate", "/kəˈlæbəreɪt/", "cộng tác", "verb", "To work with others toward a shared result.", "Designers and engineers collaborate on each feature.", "Nhà thiết kế và kỹ sư cộng tác trên từng tính năng.", "Leadership", "B1", "collaborate with"],
  ["conflict", "/ˈkɑːnflɪkt/", "xung đột", "noun", "A serious disagreement between people or groups.", "The manager addressed the conflict early.", "Người quản lý giải quyết xung đột từ sớm.", "Leadership", "B2", "resolve conflict"],
  ["solution", "/səˈluːʃən/", "giải pháp", "noun", "A way of solving a problem.", "The team found a practical solution.", "Nhóm đã tìm ra một giải pháp thiết thực.", "Leadership", "B1", "find a solution"],
  ["outcome", "/ˈaʊtkʌm/", "kết quả", "noun", "The final result of an action or process.", "The meeting produced a positive outcome.", "Cuộc họp mang lại một kết quả tích cực.", "Leadership", "B2", "desired outcome"],
  ["accountable", "/əˈkaʊntəbəl/", "chịu trách nhiệm", "adjective", "Required to explain decisions and accept responsibility for results.", "Each team leader is accountable for the final report.", "Mỗi trưởng nhóm chịu trách nhiệm về báo cáo cuối cùng.", "Leadership", "C1", "hold accountable"],
];

export const moreVocabulary = words.map(([
  word, ipa, meaning, partOfSpeech, definition, example, translation, category, level, collocation,
], index) => ({
  id: `vy${String(index + 1).padStart(3, "0")}`,
  word,
  ipa,
  meaning,
  definition,
  partOfSpeech,
  example,
  translation,
  category,
  level,
  synonyms: [],
  antonyms: [],
  collocations: [collocation],
  wordFamily: [],
}));
